import type { SeedCourse } from './types.js';

export const A0_COURSE: SeedCourse = {
  cefrLevel: 'A0',
  name: 'Španielčina A0',
  modules: [
    {
      slug: 'first-words',
      title: 'Prvé slová',
      description: 'Pozdrav, zdvorilosť a dobrý prvý dojem.',
      lessons: [
        {
          title: 'Prvé slová',
          description: 'Tvoje prvé španielske slová: pozdravy a zdvorilostné výrazy.',
          day: 1,
          minutes: 20,
          grammar: {
            slug: 'polite_expressions',
            title: 'Zdvorilostné výrazy',
            explanation:
              'Zdvorilosť je v španielčine jednoduchá: povedz "por favor", keď o niečo slušne žiadaš, a "gracias", keď ďakuješ. Môžeš ich aj spojiť: "Sí, por favor" alebo "No, gracias".',
            rule:
              '"Por favor" = prosím · "Gracias" = ďakujem · "De nada" = niet za čo. Nauč sa tieto slovné spojenia naspamäť a používaj ich všade.',
            examples: [
              { spanish: 'Sí, por favor.', translation: 'Áno, prosím.' },
              { spanish: 'No, gracias.', translation: 'Nie, ďakujem.' },
              { spanish: 'Gracias, de nada.', translation: 'Ďakujem, niet za čo.' },
            ],
          },
          vocab: [
            { spanish: 'hola', translation: 'ahoj', pronunciation: 'OH-lah', example: '¡Hola! Buenos días.', exampleTranslation: 'Ahoj! Dobré ráno.', category: 'greetings' },
            { spanish: 'buenos días', translation: 'dobré ráno', pronunciation: 'BWEH-nos DEE-ahs', example: 'Buenos días, señor.', exampleTranslation: 'Dobré ráno, pán.', category: 'greetings' },
            { spanish: 'buenas tardes', translation: 'dobré popoludnie', pronunciation: 'BWEH-nas TAR-des', example: 'Buenas tardes, ¿cómo está?', exampleTranslation: 'Dobré popoludnie, ako sa máte?', category: 'greetings' },
            { spanish: 'buenas noches', translation: 'dobrý večer / dobrú noc', pronunciation: 'BWEH-nas NO-ches', example: 'Buenas noches, hasta mañana.', exampleTranslation: 'Dobrú noc, do zajtra.', category: 'greetings' },
            { spanish: 'adiós', translation: 'dovidenia', pronunciation: 'ah-dee-OS', example: 'Adiós, nos vemos.', exampleTranslation: 'Dovidenia, uvidíme sa.', category: 'greetings' },
            { spanish: 'por favor', translation: 'prosím', pronunciation: 'por fah-VOR', example: 'Un café, por favor.', exampleTranslation: 'Jednu kávu, prosím.', category: 'politeness' },
            { spanish: 'gracias', translation: 'ďakujem', pronunciation: 'GRAH-syahs', example: 'Gracias por todo.', exampleTranslation: 'Ďakujem za všetko.', category: 'politeness' },
            { spanish: 'de nada', translation: 'niet za čo', pronunciation: 'deh NAH-dah', example: '—Gracias. —De nada.', exampleTranslation: '—Ďakujem. —Niet za čo.', category: 'politeness' },
            { spanish: 'sí', translation: 'áno', pronunciation: 'SEE', example: 'Sí, quiero café.', exampleTranslation: 'Áno, chcem kávu.', category: 'basics' },
            { spanish: 'no', translation: 'nie', pronunciation: 'NO', example: 'No, gracias.', exampleTranslation: 'Nie, ďakujem.', category: 'basics' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieme po španielsky "ahoj"?', options: ['Hola', 'Adiós', 'Gracias', 'No'], correct: 'Hola', vocab: 'hola', explanation: '"Hola" je najčastejší pozdrav.' },
            { type: 'multiple_choice', prompt: 'Kedy sa používa "buenos días"?', options: ['Ráno', 'V noci', 'Keď sa lúčiš', 'Keď kýchneš'], correct: 'Ráno', explanation: '"Buenos días" sa používa ráno, približne do obeda.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: ďakujem', correct: 'gracias', vocab: 'gracias', explanation: '"Gracias" znamená ďakujem.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: prosím', correct: 'por favor', vocab: 'por favor', explanation: '"Por favor" znamená prosím.' },
            { type: 'fill_blank', prompt: 'Doplň: — Gracias. — De ___.', correct: 'nada', vocab: 'de nada', explanation: '"De nada" je odpoveď na "gracias".' },
            { type: 'multiple_choice', prompt: 'Ktoré znamená "dobrý večer / dobrú noc"?', options: ['Buenos días', 'Buenas noches', 'Adiós', 'Hola'], correct: 'Buenas noches', vocab: 'buenas noches', explanation: '"Buenas noches" sa používa večer a v noci.' },
            { type: 'multiple_choice', prompt: 'Aká je slušná spôsob objednania kávy?', options: ['Café, por favor', 'Café, gracias', 'Café, adiós', 'Café, sí'], correct: 'Café, por favor', vocab: 'por favor', explanation: 'Pridaj "por favor", keď o niečo žiadaš.' },
            { type: 'fill_blank', prompt: 'Doplň: ___ (áno), quiero café.', correct: 'Sí', vocab: 'sí', explanation: '"Sí" znamená áno.' },
            { type: 'multiple_choice', prompt: 'Ktorý výraz sa používa, keď ďakuješ a chceš odpovedať "niet za čo"?', options: ['de nada', 'por favor', 'adiós', 'hola'], correct: 'de nada', grammar: 'polite_expressions', explanation: '"De nada" je odpoveď na "gracias".' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Hola, buenos días.', 'Hola, buenas noches.', 'Adiós, gracias.', 'No, por favor.'], correct: 'Hola, buenos días.', audioText: 'Hola, buenos días.', vocab: 'hola', explanation: 'Počul si pozdrav "Hola, buenos días".' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Un café, por favor.', 'Un café, gracias.', 'Dos cafés, por favor.', 'Café, no gracias.'], correct: 'Un café, por favor.', audioText: 'Un café, por favor.', vocab: 'por favor', explanation: 'Pri objednávke pridáš "por favor".' },
            { type: 'speaking', prompt: 'Zopakuj po španielsky: Dobré ráno.', audioText: 'Buenos días.', correct: 'Buenos días.', vocab: 'buenos días', hint: 'Povedz "Buenos días".' },
          ],
        },
        {
          title: 'Ako sa máš?',
          description: 'Pozdrav ľudí a povedz, ako sa cítiš.',
          day: 2,
          minutes: 25,
          grammar: {
            slug: 'subject_pronouns',
            title: 'Osobné zámená (podmet)',
            explanation:
              'Španielčina má osobné zámená: yo (ja), tú (ty), él (on), ella (ona), usted (vy, formálne), nosotros (my), ellos (oni).',
            rule:
              'V španielčine zámeno väčšinou NEhovoríš — koncovka slovesa už prezradí, kto je podmet. "Estoy bien" (som dobre) je prirodzenejšie ako "Yo estoy bien".',
            examples: [
              { spanish: '¿Cómo estás?', translation: 'Ako sa máš?' },
              { spanish: 'Estoy bien, gracias.', translation: 'Som dobre, ďakujem.' },
              { spanish: 'Él está muy bien.', translation: 'On je veľmi dobre.' },
            ],
          },
          vocab: [
            { spanish: '¿cómo estás?', translation: 'ako sa máš? (neformálne)', pronunciation: 'KOH-moh es-TAS', example: '¿Cómo estás, María?', exampleTranslation: 'Ako sa máš, María?', category: 'greetings' },
            { spanish: 'estoy bien', translation: 'som dobre', pronunciation: 'es-TOY bee-EN', example: 'Estoy bien, gracias.', exampleTranslation: 'Som dobre, ďakujem.', category: 'feelings' },
            { spanish: 'muy bien', translation: 'veľmi dobre', pronunciation: 'moo-ee bee-EN', example: '—¿Qué tal? —Muy bien.', exampleTranslation: '—Ako to ide? —Veľmi dobre.', category: 'feelings' },
            { spanish: 'así así', translation: 'tak tak', pronunciation: 'ah-SEE ah-SEE', example: '—¿Cómo estás? —Así así.', exampleTranslation: '—Ako sa máš? —Tak tak.', category: 'feelings' },
            { spanish: 'mal', translation: 'zle / zle sa mám', pronunciation: 'MAL', example: 'Hoy estoy mal.', exampleTranslation: 'Dnes sa mám zle.', category: 'feelings' },
            { spanish: '¿y tú?', translation: 'a ty?', pronunciation: 'ee TOO', example: 'Estoy bien, ¿y tú?', exampleTranslation: 'Som dobre, a ty?', category: 'basics' },
            { spanish: '¿qué tal?', translation: 'ako to ide?', pronunciation: 'KEH TAL', example: '¿Qué tal estás?', exampleTranslation: 'Ako sa máš?', category: 'greetings' },
            { spanish: 'hasta luego', translation: 'vidíme sa neskôr', pronunciation: 'AS-tah LWEH-go', example: 'Hasta luego, nos vemos.', exampleTranslation: 'Vidíme sa neskôr, uvidíme sa.', category: 'greetings' },
            { spanish: 'hasta mañana', translation: 'do zajtra', pronunciation: 'AS-tah mah-NYAH-nah', example: 'Buenas noches, hasta mañana.', exampleTranslation: 'Dobrú noc, do zajtra.', category: 'greetings' },
            { spanish: 'encantado', translation: 'teší ma (spoznať ťa)', pronunciation: 'en-kan-TAH-doh', example: 'Encantado de conocerte.', exampleTranslation: 'Teší ma, že ťa spoznávam.', category: 'introductions' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako odpovieš na "¿Cómo estás?", keď sa máš dobre?', options: ['Estoy bien', 'Estoy mal', 'Buenas noches', 'Adiós'], correct: 'Estoy bien', vocab: 'estoy bien', explanation: '"Estoy bien" znamená som dobre.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: a ty?', correct: '¿Y tú?', vocab: '¿y tú?', explanation: '"¿Y tú?" vracia rovnakú otázku späť.' },
            { type: 'fill_blank', prompt: 'Doplň: — ¿Qué tal? — Muy ___.', correct: 'bien', vocab: 'muy bien', explanation: '"Muy bien" znamená veľmi dobre.' },
            { type: 'multiple_choice', prompt: 'Ktoré znamená "tak tak"?', options: ['así así', 'muy bien', 'mal', 'hasta luego'], correct: 'así así', vocab: 'así así', explanation: '"Así así" vyjadruje neutrálny pocit.' },
            { type: 'multiple_choice', prompt: 'Čo poviete, keď sa lúčite a uvidíte sa neskôr?', options: ['Hasta luego', 'Buenos días', 'Gracias', 'Sí'], correct: 'Hasta luego', vocab: 'hasta luego', explanation: '"Hasta luego" znamená vidíme sa neskôr.' },
            { type: 'fill_blank', prompt: 'Doplň: ___ (teší ma) de conocerte.', correct: 'Encantado', vocab: 'encantado', explanation: '"Encantado" vyjadruje potešenie zo spoznania.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: do zajtra', correct: 'hasta mañana', vocab: 'hasta mañana', explanation: '"Hasta mañana" znamená do zajtra.' },
            { type: 'multiple_choice', prompt: 'Ktorá veta je v španielčine najprirodzenejšia pre "som dobre"?', options: ['Estoy bien', 'Yo estoy bien', 'Yo bien', 'Sí estoy'], correct: 'Estoy bien', grammar: 'subject_pronouns', explanation: 'Španielčina zámeno podmetu vynecháva — koncovka slovesa prezradí osobu.' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Estoy bien, gracias.', 'Estoy mal, gracias.', 'Muy bien, ¿y tú?', 'Así así.'], correct: 'Estoy bien, gracias.', audioText: 'Estoy bien, gracias.', vocab: 'estoy bien', explanation: 'Počul si "Estoy bien, gracias" — som dobre, ďakujem.' },
            { type: 'listening', prompt: 'Vypočuj si otázku a vyber, čo si počul.', options: ['¿Cómo estás?', '¿Qué tal?', '¿Cómo te llamas?', '¿De dónde eres?'], correct: '¿Cómo estás?', audioText: '¿Cómo estás?', vocab: '¿cómo estás?', explanation: 'Otázka "¿Cómo estás?" sa pýta, ako sa máš.' },
            { type: 'speaking', prompt: 'Zopakuj po španielsky: Som dobre, ďakujem.', audioText: 'Estoy bien, gracias.', correct: 'Estoy bien, gracias.', vocab: 'estoy bien', hint: 'Povedz "Estoy bien, gracias".' },
          ],
        },
      ],
    },
    {
      slug: 'introductions',
      title: 'Predstavovanie',
      description: 'Povedz, kto si, opýtaj sa na meno a odkiaľ si.',
      lessons: [
        {
          title: 'Volám sa…',
          description: 'Predstav sa a nauč sa sloveso ser.',
          day: 3,
          minutes: 30,
          grammar: {
            slug: 'ser',
            title: 'Sloveso ser (byť) — 1. časť',
            explanation:
              'Ser sa používa na povedanie KTO alebo ČO je niekto: mená, identita, národnosť a povolanie. Je to sloveso, ktoré potrebuješ na predstavenie sa.',
            rule: 'yo soy = ja som · tú eres = ty si · él/ella es = on/ona je. Príklad: "Yo soy Erik." → "Soy Erik."',
            examples: [
              { spanish: 'Soy Erik.', translation: 'Som Erik.' },
              { spanish: 'Tú eres Ana.', translation: 'Ty si Ana.' },
              { spanish: 'Ella es María.', translation: 'Ona je María.' },
            ],
          },
          vocab: [
            { spanish: 'me llamo', translation: 'volám sa', pronunciation: 'meh YAH-moh', example: 'Me llamo Pablo.', exampleTranslation: 'Volám sa Pablo.', category: 'introductions' },
            { spanish: '¿cómo te llamas?', translation: 'ako sa voláš?', pronunciation: 'KOH-moh teh YAH-mas', example: '¿Cómo te llamas?', exampleTranslation: 'Ako sa voláš?', category: 'introductions' },
            { spanish: 'se llama', translation: 'volá sa', pronunciation: 'seh YAH-mah', example: 'Se llama Carmen.', exampleTranslation: 'Volá sa Carmen.', category: 'introductions' },
            { spanish: 'nombre', translation: 'meno', pronunciation: 'NOM-breh', example: 'Mi nombre es Luis.', exampleTranslation: 'Moje meno je Luis.', category: 'introductions' },
            { spanish: 'mucho gusto', translation: 'teší ma', pronunciation: 'MOO-choh GOOS-toh', example: '—Me llamo Ana. —Mucho gusto.', exampleTranslation: '—Volám sa Ana. —Teší ma.', category: 'introductions' },
            { spanish: 'igualmente', translation: 'mňa tiež (rovnako)', pronunciation: 'ee-gwahl-MEN-teh', example: '—Mucho gusto. —Igualmente.', exampleTranslation: '—Teší ma. —Mňa tiež.', category: 'introductions' },
            { spanish: 'yo', translation: 'ja', pronunciation: 'yoh', example: 'Yo soy de España.', exampleTranslation: 'Ja som zo Španielska.', category: 'basics' },
            { spanish: 'tú', translation: 'ty (neformálne)', pronunciation: 'TOO', example: 'Tú eres muy amable.', exampleTranslation: 'Ty si veľmi milý.', category: 'basics' },
            { spanish: 'él', translation: 'on', pronunciation: 'EL', example: 'Él es mi hermano.', exampleTranslation: 'On je môj brat.', category: 'basics' },
            { spanish: 'ella', translation: 'ona', pronunciation: 'EH-yah', example: 'Ella es mi hermana.', exampleTranslation: 'Ona je moja sestra.', category: 'basics' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieme "volám sa Erik"?', options: ['Me llamo Erik', 'Yo llamo Erik', 'Erik me llama', 'Tu llamo Erik'], correct: 'Me llamo Erik', vocab: 'me llamo', explanation: '"Me llamo" = volám sa. Sloveso je "llamarse".' },
            { type: 'translation', prompt: 'Prelož do španielčiny: volám sa', correct: 'me llamo', vocab: 'me llamo', explanation: '"Me llamo" doslova znamená "volám si" (zvratné sloveso).' },
            { type: 'fill_blank', prompt: 'Doplň: ¿Cómo ___ llamas?', correct: 'te', vocab: '¿cómo te llamas?', explanation: '"¿Cómo te llamas?" = ako sa voláš?' },
            { type: 'multiple_choice', prompt: 'Ktorý tvar je správny pre "ja som" (ser)?', options: ['soy', 'eres', 'es', 'son'], correct: 'soy', grammar: 'ser', explanation: 'yo soy, tú eres, él/ella es.' },
            { type: 'fill_blank', prompt: 'Doplň správny tvar ser: Yo ___ Erik.', correct: 'soy', grammar: 'ser', explanation: 'S "yo" používame "soy".' },
            { type: 'multiple_choice', prompt: 'Ako odpovieš na "Mucho gusto"?', options: ['Igualmente', 'De nada', 'Buenas noches', 'Por favor'], correct: 'Igualmente', vocab: 'igualmente', explanation: '"Igualmente" = mňa tiež. Je to zdvorilá odpoveď.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: teší ma', correct: 'mucho gusto', vocab: 'mucho gusto', explanation: '"Mucho gusto" sa používa pri prvom stretnutí.' },
            { type: 'multiple_choice', prompt: 'Ktoré znamená "ona"?', options: ['ella', 'él', 'tú', 'yo'], correct: 'ella', vocab: 'ella', explanation: '"Ella" = ona, "él" = on.' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Me llamo Erik.', 'Me llamo Ana.', 'Soy Erik.', '¿Cómo te llamas?'], correct: 'Me llamo Erik.', audioText: 'Me llamo Erik.', vocab: 'me llamo', explanation: 'Počul si predstavenie "Me llamo Erik".' },
            { type: 'listening', prompt: 'Vypočuj si otázku a vyber, čo si počul.', options: ['¿Cómo te llamas?', '¿Qué tal?', '¿De dónde eres?', '¿Cómo estás?'], correct: '¿Cómo te llamas?', audioText: '¿Cómo te llamas?', vocab: '¿cómo te llamas?', explanation: 'Otázka "¿Cómo te llamas?" sa pýta na meno.' },
            { type: 'speaking', prompt: 'Zopakuj po španielsky: Teší ma.', audioText: 'Mucho gusto.', correct: 'Mucho gusto.', vocab: 'mucho gusto', hint: 'Povedz "Mucho gusto".' },
          ],
        },
        {
          title: 'Odkiaľ si?',
          description: 'Povedz, odkiaľ si, pomocou ser + de.',
          day: 4,
          minutes: 30,
          grammar: {
            slug: 'origin_de',
            title: 'Odkiaľ si: ser + de',
            explanation:
              'Keď chceš povedať, odkiaľ si, použiješ "soy de" (som z) + krajina. Sloveso "ser" sa nemení, mení sa len krajina.',
            rule: 'soy de + krajina = som z… Príklad: "Soy de Eslovaquia." Opýtaš sa: "¿De dónde eres?"',
            examples: [
              { spanish: '¿De dónde eres?', translation: 'Odkiaľ si?' },
              { spanish: 'Soy de España.', translation: 'Som zo Španielska.' },
              { spanish: 'Ella es de México.', translation: 'Ona je z Mexika.' },
            ],
          },
          vocab: [
            { spanish: 'país', translation: 'krajina', pronunciation: 'pah-EES', example: 'España es mi país.', exampleTranslation: 'Španielsko je moja krajina.', category: 'countries' },
            { spanish: '¿de dónde eres?', translation: 'odkiaľ si?', pronunciation: 'deh DON-deh EH-res', example: '¿De dónde eres, Ana?', exampleTranslation: 'Odkiaľ si, Ana?', category: 'introductions' },
            { spanish: 'soy de', translation: 'som z', pronunciation: 'soy deh', example: 'Soy de Eslovaquia.', exampleTranslation: 'Som zo Slovenska.', category: 'introductions' },
            { spanish: 'España', translation: 'Španielsko', pronunciation: 'es-PAH-nyah', example: 'España es un país bonito.', exampleTranslation: 'Španielsko je krásna krajina.', category: 'countries' },
            { spanish: 'Eslovaquia', translation: 'Slovensko', pronunciation: 'es-loh-VAH-kee-ah', example: 'Soy de Eslovaquia.', exampleTranslation: 'Som zo Slovenska.', category: 'countries' },
            { spanish: 'México', translation: 'Mexiko', pronunciation: 'MEH-hee-koh', example: 'Él es de México.', exampleTranslation: 'On je z Mexika.', category: 'countries' },
            { spanish: 'Argentina', translation: 'Argentína', pronunciation: 'ar-hen-TEE-nah', example: 'Ella es de Argentina.', exampleTranslation: 'Ona je z Argentíny.', category: 'countries' },
            { spanish: 'Estados Unidos', translation: 'Spojené štáty', pronunciation: 'es-TAH-dohs oo-NEE-dohs', example: '¿Eres de Estados Unidos?', exampleTranslation: 'Si zo Spojených štátov?', category: 'countries' },
            { spanish: 'Inglaterra', translation: 'Anglicko', pronunciation: 'een-glah-TEH-rrah', example: 'Mis amigos son de Inglaterra.', exampleTranslation: 'Moji kamaráti sú z Anglicka.', category: 'countries' },
            { spanish: 'Francia', translation: 'Francúzsko', pronunciation: 'FRAHN-syah', example: 'Soy de Francia.', exampleTranslation: 'Som z Francúzska.', category: 'countries' },
          ],
          exercises: [
            { type: 'translation', prompt: 'Prelož do španielčiny: som zo Španielska', correct: 'Soy de España', vocab: 'soy de', explanation: '"Soy de" + krajina = som z.' },
            { type: 'multiple_choice', prompt: 'Ako sa opýtaš "odkiaľ si?"', options: ['¿De dónde eres?', '¿Cómo te llamas?', '¿Qué tal?', '¿Cómo estás?'], correct: '¿De dónde eres?', vocab: '¿de dónde eres?', explanation: '"¿De dónde eres?" sa pýta na pôvod.' },
            { type: 'fill_blank', prompt: 'Doplň: Soy ___ Eslovaquia.', correct: 'de', vocab: 'soy de', explanation: 'Po "soy" použijeme "de" (z).' },
            { type: 'multiple_choice', prompt: 'Ella ___ de Argentina. (doplň ser)', options: ['es', 'soy', 'eres', 'son'], correct: 'es', grammar: 'ser', explanation: 'S "ella" používame "es".' },
            { type: 'fill_blank', prompt: 'Doplň: ¿De dónde ___? (ty)', correct: 'eres', grammar: 'ser', explanation: 'S "tú" používame "eres".' },
            { type: 'translation', prompt: 'Prelož do španielčiny: krajina', correct: 'país', vocab: 'país', explanation: '"País" znamená krajina.' },
            { type: 'multiple_choice', prompt: 'Ktorá krajina NIE je v slovíčkach tejto lekcie?', options: ['Alemania', 'México', 'Francia', 'España'], correct: 'Alemania', vocab: 'país', explanation: 'Nemecko (Alemania) príde v neskoršej lekcii.' },
            { type: 'multiple_choice', prompt: '"Soy de España" znamená…', options: ['Som zo Španielska', 'Idem do Španielska', 'Mám rád Španielsko', 'Bývam v Španielsku'], correct: 'Som zo Španielska', vocab: 'soy de', explanation: '"Soy de" vyjadruje pôvod.' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Soy de España.', 'Soy de Eslovaquia.', 'Soy de México.', 'Soy de Francia.'], correct: 'Soy de España.', audioText: 'Soy de España.', vocab: 'España', explanation: 'Počul si "Soy de España" — som zo Španielska.' },
            { type: 'listening', prompt: 'Vypočuj si otázku a vyber, čo si počul.', options: ['¿De dónde eres?', '¿Cómo te llamas?', '¿Qué tal?', '¿Cómo estás?'], correct: '¿De dónde eres?', audioText: '¿De dónde eres?', vocab: '¿de dónde eres?', explanation: 'Otázka "¿De dónde eres?" sa pýta na pôvod.' },
            { type: 'speaking', prompt: 'Zopakuj po španielsky: Som zo Slovenska.', audioText: 'Soy de Eslovaquia.', correct: 'Soy de Eslovaquia.', vocab: 'soy de', hint: 'Povedz "Soy de Eslovaquia".' },
          ],
        },
      ],
    },
    {
      slug: 'week-1-review',
      title: 'Týždeň 1 — opakovanie',
      description: 'Spoj naučené vety do prvého rozhovoru.',
      lessons: [
        {
          title: 'Mini rozhovor',
          description: 'Zlož prvé vety do celého rozhovoru a precvič si predstavenie.',
          day: 5,
          minutes: 25,
          grammar: {
            slug: 'conversation_combos',
            title: 'Prvý rozhovor',
            explanation:
              'Predstavenie je kombinácia troch kúskov: ako sa volášš (me llamo), odkiaľ si (soy de) a zdvorilé "teší ma" (mucho gusto) s odpoveďou "igualmente".',
            rule: '¿Cómo te llamas? → Me llamo… · ¿De dónde eres? → Soy de… · Mucho gusto. → Igualmente. Prečítaj rozhovor nahlas a striedaj úlohy.',
            examples: [
              { spanish: '—Hola, ¿cómo te llamas? —Me llamo Erik. —Mucho gusto.', translation: '—Ahoj, ako sa voláš? —Volám sa Erik. —Teší ma.' },
              { spanish: '—¿De dónde eres? —Soy de Eslovaquia. —¡Qué bien!', translation: '—Odkiaľ si? —Som zo Slovenska. —Aké dobré!' },
              { spanish: '—Mucho gusto, Ana. —Igualmente.', translation: '—Teší ma, Ana. —Mňa tiež.' },
            ],
          },
          vocab: [
            { spanish: 'mucho gusto', translation: 'teší ma', pronunciation: 'MOO-choh GOOS-toh', example: 'Mucho gusto, señor.', exampleTranslation: 'Teší ma, pán.', category: 'introductions' },
            { spanish: 'igualmente', translation: 'mňa tiež', pronunciation: 'ee-gwahl-MEN-teh', example: '—Mucho gusto. —Igualmente.', exampleTranslation: '—Teší ma. —Mňa tiež.', category: 'introductions' },
            { spanish: 'también', translation: 'tiež', pronunciation: 'tam-bee-EN', example: 'Yo también soy de aquí.', exampleTranslation: 'Ja som tiež odtiaľto.', category: 'basics' },
            { spanish: 'encantado', translation: 'teší ma (spoznať ťa)', pronunciation: 'en-kan-TAH-doh', example: 'Encantado de conocerte.', exampleTranslation: 'Teší ma, že ťa spoznávam.', category: 'introductions' },
            { spanish: 'bien', translation: 'dobre', pronunciation: 'bee-EN', example: 'Estoy muy bien.', exampleTranslation: 'Mám sa veľmi dobre.', category: 'feelings' },
            { spanish: 'muy', translation: 'veľmi', pronunciation: 'moo-ee', example: 'Estoy muy bien.', exampleTranslation: 'Mám sa veľmi dobre.', category: 'basics' },
            { spanish: '¿y tú?', translation: 'a ty?', pronunciation: 'ee TOO', example: 'Soy de Eslovaquia, ¿y tú?', exampleTranslation: 'Som zo Slovenska, a ty?', category: 'basics' },
            { spanish: 'nos vemos', translation: 'uvidíme sa', pronunciation: 'nos BEH-mos', example: 'Adiós, nos vemos.', exampleTranslation: 'Dovidenia, uvidíme sa.', category: 'greetings' },
          ],
          exercises: [
            { type: 'fill_blank', prompt: 'Doplň: Mucho ___. (teší ma)', correct: 'gusto', vocab: 'mucho gusto', explanation: '"Mucho gusto" = teší ma.' },
            { type: 'multiple_choice', prompt: 'Ako odpovieš na "Mucho gusto"?', options: ['Igualmente', 'De nada', 'No, gracias', 'Buenas noches'], correct: 'Igualmente', vocab: 'igualmente', explanation: '"Igualmente" = mňa tiež.' },
            { type: 'multiple_choice', prompt: 'Ktorá veta je správne predstavenie?', options: ['Me llamo Erik', 'Yo Erik llamo', 'Erik se me llama', 'Me llamo es Erik'], correct: 'Me llamo Erik', vocab: 'mucho gusto', explanation: '"Me llamo + meno" je správne predstavenie.' },
            { type: 'fill_blank', prompt: 'Doplň: Soy ___ Eslovaquia.', correct: 'de', vocab: 'mucho gusto', explanation: 'Po "soy" nasleduje "de" (z).' },
            { type: 'translation', prompt: 'Prelož do španielčiny: a ty?', correct: '¿Y tú?', vocab: '¿y tú?', explanation: '"¿Y tú?" vracia otázku späť.' },
            { type: 'multiple_choice', prompt: '"Igualmente" znamená…', options: ['mňa tiež', 'niet za čo', 'dovidenia', 'prosím'], correct: 'mňa tiež', vocab: 'igualmente', explanation: '"Igualmente" sa používa ako odpoveď na "mucho gusto".' },
            { type: 'multiple_choice', prompt: 'Ako sa opýtaš na meno?', options: ['¿Cómo te llamas?', '¿De dónde eres?', '¿Qué hora es?', '¿Cuánto cuesta?'], correct: '¿Cómo te llamas?', vocab: 'encantado', explanation: '"¿Cómo te llamas?" = ako sa voláš?' },
            { type: 'translation', prompt: 'Prelož do španielčiny: som zo Slovenska', correct: 'Soy de Eslovaquia', vocab: 'encantado', explanation: '"Soy de Eslovaquia" = som zo Slovenska.' },
            { type: 'multiple_choice', prompt: 'Ktorá dvojica tvorí celý rozhovor predstavenia?', options: ['¿Cómo te llamas? — Me llamo Ana.', '¿Qué hora es? — Es la una.', '¿Cuánto cuesta? — Cinco euros.', '¿De qué color? — Azul.'], correct: '¿Cómo te llamas? — Me llamo Ana.', grammar: 'conversation_combos', explanation: 'Rozhovor začína otázkou na meno a odpoveďou "Me llamo…".' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Mucho gusto, Ana.', 'Mucho gusto, Erik.', 'Encantado, Ana.', 'Igualmente, Ana.'], correct: 'Mucho gusto, Ana.', audioText: 'Mucho gusto, Ana.', vocab: 'mucho gusto', explanation: 'Počul si zdvorilé "Mucho gusto, Ana" — teší ma, Ana.' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Nos vemos.', 'Hasta mañana.', 'Buenas noches.', 'Adiós, nos vemos.'], correct: 'Nos vemos.', audioText: 'Nos vemos.', vocab: 'nos vemos', explanation: '"Nos vemos" znamená uvidíme sa.' },
            { type: 'speaking', prompt: 'Zopakuj po španielsky: Mňa tiež.', audioText: 'Igualmente.', correct: 'Igualmente.', vocab: 'igualmente', hint: 'Povedz "Igualmente".' },
          ],
        },
      ],
    },
    {
      slug: 'family-friends',
      title: 'Rodina a priatelia',
      description: 'Hovor o svojej rodine, používaj privlastňovanie a opisuj ľudí.',
      lessons: [
        {
          title: 'Moja rodina',
          description: 'Nauč sa rodinné slová a ako povedať "môj", "tvoj" a "jeho/jej".',
          day: 6,
          minutes: 30,
          grammar: {
            slug: 'possessives',
            title: 'Privlastňovacie zámená: mi, tu, su',
            explanation:
              'Na vyjadrenie vlastníctva používame "mi" (môj), "tu" (tvoj), "su" (jeho/jej/ich). Zhodujú sa v čísle: "mi" → "mis" pred množným číslom.',
            rule: 'mi / mis = môj · tu / tus = tvoj · su / sus = jeho, jej, ich. Príklad: mi hermano, mis hermanos, tu hermana.',
            examples: [
              { spanish: 'Mi hermano es alto.', translation: 'Môj brat je vysoký.' },
              { spanish: 'Mis hermanas son simpáticas.', translation: 'Moje sestry sú milé.' },
              { spanish: '¿Cómo se llama tu madre?', translation: 'Ako sa volá tvoja matka?' },
            ],
          },
          vocab: [
            { spanish: 'familia', translation: 'rodina', pronunciation: 'fah-MEE-lee-ah', example: 'Mi familia es grande.', exampleTranslation: 'Moja rodina je veľká.', category: 'family' },
            { spanish: 'madre', translation: 'matka', pronunciation: 'MAH-dreh', example: 'Mi madre se llama Rosa.', exampleTranslation: 'Moja matka sa volá Rosa.', category: 'family' },
            { spanish: 'padre', translation: 'otec', pronunciation: 'PAH-dreh', example: 'Mi padre es de España.', exampleTranslation: 'Môj otec je zo Španielska.', category: 'family' },
            { spanish: 'hermano', translation: 'brat', pronunciation: 'er-MAH-noh', example: 'Tengo un hermano.', exampleTranslation: 'Mám jedného brata.', category: 'family' },
            { spanish: 'hermana', translation: 'sestra', pronunciation: 'er-MAH-nah', example: 'Mi hermana es muy joven.', exampleTranslation: 'Moja sestra je veľmi mladá.', category: 'family' },
            { spanish: 'hijo', translation: 'syn', pronunciation: 'EE-hoh', example: 'Mi hijo tiene diez años.', exampleTranslation: 'Môj syn má desať rokov.', category: 'family' },
            { spanish: 'hija', translation: 'dcéra', pronunciation: 'EE-hah', example: 'Su hija es estudiante.', exampleTranslation: 'Jeho dcéra je študentka.', category: 'family' },
            { spanish: 'abuelo', translation: 'starý otec', pronunciation: 'ah-BWEH-loh', example: 'Mi abuelo tiene ochenta años.', exampleTranslation: 'Môj starý otec má osemdesiat rokov.', category: 'family' },
            { spanish: 'abuela', translation: 'stará mama', pronunciation: 'ah-BWEH-lah', example: 'Mi abuela es muy amable.', exampleTranslation: 'Moja stará mama je veľmi milá.', category: 'family' },
            { spanish: 'tío', translation: 'strýko', pronunciation: 'TEE-oh', example: 'Mi tío vive en Francia.', exampleTranslation: 'Môj strýko býva vo Francúzsku.', category: 'family' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieme "moja rodina"?', options: ['mi familia', 'tu familia', 'su familia', 'la familia'], correct: 'mi familia', vocab: 'familia', explanation: '"Mi" = môj/moja.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: moja matka', correct: 'mi madre', vocab: 'madre', explanation: '"Mi" + madre = moja matka.' },
            { type: 'fill_blank', prompt: 'Doplň: Tengo un ___ (brat).', correct: 'hermano', vocab: 'hermano', explanation: '"Hermano" je brat; "hermana" je sestra.' },
            { type: 'multiple_choice', prompt: 'Ktoré je správne pre "moji bratia"?', options: ['mis hermanos', 'mi hermanos', 'su hermanos', 'tus hermanos'], correct: 'mis hermanos', grammar: 'possessives', explanation: 'Pred množným číslom sa "mi" mení na "mis".' },
            { type: 'multiple_choice', prompt: '"Su hija" znamená…', options: ['jeho/jej dcéra', 'moja dcéra', 'tvoj syn', 'ich syn'], correct: 'jeho/jej dcéra', grammar: 'possessives', explanation: '"Su" = jeho, jej alebo ich.' },
            { type: 'fill_blank', prompt: 'Doplň: ¿Cómo se llama ___ (tvoja) madre?', correct: 'tu', grammar: 'possessives', explanation: '"Tu" = tvoja.' },
            { type: 'multiple_choice', prompt: 'Ktoré slovo znamená "stará mama"?', options: ['abuela', 'abuelo', 'hermana', 'madre'], correct: 'abuela', vocab: 'abuela', explanation: '"Abuela" je stará mama, "abuelo" je starý otec.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: syn', correct: 'hijo', vocab: 'hijo', explanation: '"Hijo" je syn, "hija" je dcéra.' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Mi familia es grande.', 'Tu familia es grande.', 'Su familia es grande.', 'La familia es grande.'], correct: 'Mi familia es grande.', audioText: 'Mi familia es grande.', vocab: 'familia', explanation: 'Počul si "Mi familia es grande" — moja rodina je veľká.' },
            { type: 'listening', prompt: 'Vypočuj si otázku a vyber, čo si počul.', options: ['¿Cómo se llama tu madre?', '¿Cómo se llama tu padre?', '¿Cómo se llama tu hermano?', '¿Cómo te llamas?'], correct: '¿Cómo se llama tu madre?', audioText: '¿Cómo se llama tu madre?', vocab: 'madre', explanation: 'Pýta sa na meno tvojej matky.' },
            { type: 'speaking', prompt: 'Zopakuj po španielsky: Moja matka sa volá Rosa.', audioText: 'Mi madre se llama Rosa.', correct: 'Mi madre se llama Rosa.', vocab: 'madre', hint: 'Povedz "Mi madre se llama Rosa".' },
          ],
        },
        {
          title: 'Opis ľudí',
          description: 'Opisuj rodinu a kamarátov pomocou prídavných mien.',
          day: 7,
          minutes: 30,
          grammar: {
            slug: 'adjective_agreement',
            title: 'Zhoda prídavných mien',
            explanation:
              'V španielčine sa prídavné mená menia podľa rodu a čísla podstatného mena. Ženský rod dostane -a, mužský si ponechá -o a oba pridajú -s v množnom čísle.',
            rule: 'mužský -o → ženský -a: hermano alto / hermana alta · množné číslo + s: hermanos altos. Prídavné meno zvyčajne stojí za podstatným menom.',
            examples: [
              { spanish: 'El hermano mayor.', translation: 'Starší brat.' },
              { spanish: 'La hermana mayor.', translation: 'Staršia sestra.' },
              { spanish: 'Los hermanos mayores.', translation: 'Starší súrodenci.' },
            ],
          },
          vocab: [
            { spanish: 'esposo', translation: 'manžel', pronunciation: 'es-POH-soh', example: 'Mi esposo es muy simpático.', exampleTranslation: 'Môj manžel je veľmi milý.', category: 'family' },
            { spanish: 'esposa', translation: 'manželka', pronunciation: 'es-POH-sah', example: 'Su esposa es de México.', exampleTranslation: 'Jeho manželka je z Mexika.', category: 'family' },
            { spanish: 'amigo', translation: 'kamarát', pronunciation: 'ah-MEE-goh', example: 'Mi amigo es alto.', exampleTranslation: 'Môj kamarát je vysoký.', category: 'friends' },
            { spanish: 'amiga', translation: 'kamarátka', pronunciation: 'ah-MEE-gah', example: 'Mi amiga es muy inteligente.', exampleTranslation: 'Moja kamarátka je veľmi inteligentná.', category: 'friends' },
            { spanish: 'grande', translation: 'veľký', pronunciation: 'GRAHN-deh', example: 'Mi familia es grande.', exampleTranslation: 'Moja rodina je veľká.', category: 'descriptions' },
            { spanish: 'pequeño', translation: 'malý', pronunciation: 'peh-KEH-nyoh', example: 'Mi casa es pequeña.', exampleTranslation: 'Môj dom je malý.', category: 'descriptions' },
            { spanish: 'mayor', translation: 'starší', pronunciation: 'mah-YOR', example: 'Él es mi hermano mayor.', exampleTranslation: 'On je môj starší brat.', category: 'descriptions' },
            { spanish: 'menor', translation: 'mladší', pronunciation: 'meh-NOR', example: 'Ella es mi hermana menor.', exampleTranslation: 'Ona je moja mladšia sestra.', category: 'descriptions' },
            { spanish: 'alto', translation: 'vysoký', pronunciation: 'AL-toh', example: 'Mi padre es alto.', exampleTranslation: 'Môj otec je vysoký.', category: 'descriptions' },
            { spanish: 'simpático', translation: 'milý / sympatický', pronunciation: 'sim-PAH-tee-koh', example: 'Tus amigos son simpáticos.', exampleTranslation: 'Tvoji kamaráti sú milí.', category: 'descriptions' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieme "moja staršia sestra"?', options: ['mi hermana mayor', 'mi hermano mayor', 'mi mayor hermana', 'la hermana mía mayor'], correct: 'mi hermana mayor', grammar: 'adjective_agreement', explanation: 'Prídavné meno stojí za podstatným: hermana mayor.' },
            { type: 'multiple_choice', prompt: 'Ženský tvar od "alto" je…', options: ['alta', 'alto', 'altos', 'altas'], correct: 'alta', grammar: 'adjective_agreement', explanation: '-o sa mení na -a pre ženský rod.' },
            { type: 'multiple_choice', prompt: 'Množné číslo od "amiga simpática" je…', options: ['amigas simpáticas', 'amigos simpáticos', 'amigas simpática', 'amigas simpático'], correct: 'amigas simpáticas', grammar: 'adjective_agreement', explanation: 'Obe slová sa zhodujú v rode aj čísle.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: manžel', correct: 'esposo', vocab: 'esposo', explanation: 'Esposo = manžel, esposa = manželka.' },
            { type: 'fill_blank', prompt: 'Doplň: Mi ___ (kamarátka) es inteligente.', correct: 'amiga', vocab: 'amiga', explanation: 'Pre kamarátku (žena) používame "amiga".' },
            { type: 'multiple_choice', prompt: '"Mi casa es pequeña" znamená…', options: ['Môj dom je malý', 'Môj dom je veľký', 'Môj dom je starý', 'Môj dom je nový'], correct: 'Môj dom je malý', vocab: 'pequeño', explanation: 'Pequeña (ženský rod) = malá.' },
            { type: 'fill_blank', prompt: 'Doplň: Ella es mi hermana ___ (mladšia).', correct: 'menor', vocab: 'menor', explanation: '"Menor" = mladší.' },
            { type: 'multiple_choice', prompt: 'Ktoré prídavné meno znamená "milý / sympatický"?', options: ['simpático', 'grande', 'alto', 'menor'], correct: 'simpático', vocab: 'simpático', explanation: '"Simpático" = milý, sympatický.' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Mi casa es pequeña.', 'Mi casa es grande.', 'Tu casa es pequeña.', 'Su casa es pequeña.'], correct: 'Mi casa es pequeña.', audioText: 'Mi casa es pequeña.', vocab: 'pequeño', explanation: 'Počul si "Mi casa es pequeña" — môj dom je malý.' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Él es mi hermano mayor.', 'Él es mi hermano menor.', 'Él es mi padre.', 'Ella es mi hermana mayor.'], correct: 'Él es mi hermano mayor.', audioText: 'Él es mi hermano mayor.', vocab: 'mayor', explanation: '"Él es mi hermano mayor" — on je môj starší brat.' },
            { type: 'speaking', prompt: 'Zopakuj po španielsky: Moja kamarátka je veľmi inteligentná.', audioText: 'Mi amiga es muy inteligente.', correct: 'Mi amiga es muy inteligente.', vocab: 'amiga', hint: 'Povedz "Mi amiga es muy inteligente".' },
          ],
        },
      ],
    },
    {
      slug: 'numbers',
      title: 'Čísla',
      description: 'Počítaj od nuly do dvadsať a hovor o množstvách.',
      lessons: [
        {
          title: 'Počítaj od 0 do 10',
          description: 'Nauč sa čísla a slová pre veci okolo seba.',
          day: 8,
          minutes: 30,
          grammar: {
            slug: 'articles',
            title: 'Určité členy: el, la, los, las',
            explanation:
              'Španielske podstatné mená sú mužského alebo ženského rodu. "El" aj "la" znamenajú "ten/ta" (určitý člen). "El" patrí k mužskému, "la" k ženskému rodu. V množnom čísle sú "los" a "las".',
            rule: 'el (m. jedn.) → los (m. mn.) · la (ž. jedn.) → las (ž. mn.). Príklad: el número, la casa, los números, las casas.',
            examples: [
              { spanish: 'el número', translation: 'číslo' },
              { spanish: 'la casa', translation: 'dom' },
              { spanish: 'los números', translation: 'čísla' },
            ],
          },
          vocab: [
            { spanish: 'cero', translation: 'nula', pronunciation: 'SEH-roh', example: 'Cero es un número.', exampleTranslation: 'Nula je číslo.', category: 'numbers' },
            { spanish: 'uno', translation: 'jeden', pronunciation: 'OO-noh', example: 'Tengo un café.', exampleTranslation: 'Mám jednu kávu.', category: 'numbers' },
            { spanish: 'dos', translation: 'dva', pronunciation: 'DOS', example: 'Dos cafés, por favor.', exampleTranslation: 'Dve kávy, prosím.', category: 'numbers' },
            { spanish: 'tres', translation: 'tri', pronunciation: 'TRES', example: 'Tres amigos.', exampleTranslation: 'Traja kamaráti.', category: 'numbers' },
            { spanish: 'cuatro', translation: 'štyri', pronunciation: 'KWAH-troh', example: 'Cuatro sillas.', exampleTranslation: 'Štyri stoličky.', category: 'numbers' },
            { spanish: 'cinco', translation: 'päť', pronunciation: 'SEEN-koh', example: 'Cinco euros.', exampleTranslation: 'Päť eur.', category: 'numbers' },
            { spanish: 'seis', translation: 'šesť', pronunciation: 'SAYSS', example: 'Seis días.', exampleTranslation: 'Šesť dní.', category: 'numbers' },
            { spanish: 'siete', translation: 'sedem', pronunciation: 'see-EH-teh', example: 'Siete hermanos.', exampleTranslation: 'Sedem súrodencov.', category: 'numbers' },
            { spanish: 'ocho', translation: 'osem', pronunciation: 'OH-choh', example: 'Ocho horas.', exampleTranslation: 'Osem hodín.', category: 'numbers' },
            { spanish: 'nueve', translation: 'deväť', pronunciation: 'NWEH-beh', example: 'Nueve euros.', exampleTranslation: 'Deväť eur.', category: 'numbers' },
            { spanish: 'diez', translation: 'desať', pronunciation: 'dee-ESS', example: 'Diez estudiantes.', exampleTranslation: 'Desať študentov.', category: 'numbers' },
          ],
          exercises: [
            { type: 'translation', prompt: 'Prelož do španielčiny: päť', correct: 'cinco', vocab: 'cinco', explanation: 'Cinco = päť.' },
            { type: 'multiple_choice', prompt: 'Aké číslo je "tres"?', options: ['3', '4', '5', '2'], correct: '3', vocab: 'tres', explanation: 'Tres = tri.' },
            { type: 'multiple_choice', prompt: '"Siete" znamená…', options: ['7', '6', '8', '9'], correct: '7', vocab: 'siete', explanation: 'Siete = sedem.' },
            { type: 'fill_blank', prompt: 'Doplň: dos, ___, cuatro', correct: 'tres', vocab: 'tres', explanation: 'Postupnosť je dos, tres, cuatro.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: desať', correct: 'diez', vocab: 'diez', explanation: 'Diez = desať.' },
            { type: 'multiple_choice', prompt: 'Ktorý člen patrí k "número"?', options: ['el', 'la', 'los', 'las'], correct: 'el', grammar: 'articles', explanation: '"Número" je mužského rodu → "el número".' },
            { type: 'multiple_choice', prompt: 'Množné číslo od "la casa" je…', options: ['las casas', 'los casas', 'la casas', 'el casa'], correct: 'las casas', grammar: 'articles', explanation: 'Ženský rod v množnom čísle → "las casas".' },
            { type: 'fill_blank', prompt: 'Doplň: Tengo ___ (jeden) café.', correct: 'un', grammar: 'articles', explanation: 'Číslovka "uno" sa pred mužským podstatným menom mení na "un".' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Tengo un café.', 'Tengo dos cafés.', 'Quiero un café.', 'Tengo un hermano.'], correct: 'Tengo un café.', audioText: 'Tengo un café.', vocab: 'uno', explanation: 'Počul si "Tengo un café" — mám jednu kávu.' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Cinco euros.', 'Tres euros.', 'Cinco hermanos.', 'Seis euros.'], correct: 'Cinco euros.', audioText: 'Cinco euros.', vocab: 'cinco', explanation: 'Počul si cenu "Cinco euros" — päť eur.' },
            { type: 'speaking', prompt: 'Zopakuj po španielsky: Traja kamaráti.', audioText: 'Tres amigos.', correct: 'Tres amigos.', vocab: 'tres', hint: 'Povedz "Tres amigos".' },
          ],
        },
        {
          title: 'Čísla od 11 do 20',
          description: 'Rozšír si počítanie a tvorenie množného čísla.',
          day: 9,
          minutes: 30,
          grammar: {
            slug: 'plurals',
            title: 'Tvorenie množného čísla',
            explanation:
              'Väčšina podstatných mien tvorí množné číslo pridaním -s, ak končia na samohlásku, a -es, ak končia na spoluhlásku. Mení sa aj člen: el → los, la → las.',
            rule: 'samohláska + s: casa → casas · spoluhláska + es: ciudad → ciudades. Člen sa tiež mení: la casa → las casas, el número → los números.',
            examples: [
              { spanish: 'un número, dos números', translation: 'jedno číslo, dve čísla' },
              { spanish: 'la casa, las casas', translation: 'dom, domy' },
            ],
          },
          vocab: [
            { spanish: 'once', translation: 'jedenásť', pronunciation: 'ON-seh', example: 'Once amigos.', exampleTranslation: 'Jedenásť kamarátov.', category: 'numbers' },
            { spanish: 'doce', translation: 'dvanásť', pronunciation: 'DOH-seh', example: 'Doce meses.', exampleTranslation: 'Dvanásť mesiacov.', category: 'numbers' },
            { spanish: 'trece', translation: 'trinásť', pronunciation: 'TREH-seh', example: 'Trece euros.', exampleTranslation: 'Trinásť eur.', category: 'numbers' },
            { spanish: 'catorce', translation: 'štrnásť', pronunciation: 'kah-TOR-seh', example: 'Catorce días.', exampleTranslation: 'Štrnásť dní.', category: 'numbers' },
            { spanish: 'quince', translation: 'pätnásť', pronunciation: 'KEEN-seh', example: 'Quince minutos.', exampleTranslation: 'Pätnásť minút.', category: 'numbers' },
            { spanish: 'dieciséis', translation: 'šestnásť', pronunciation: 'dee-eh-see-SAYSS', example: 'Dieciséis años.', exampleTranslation: 'Šestnásť rokov.', category: 'numbers' },
            { spanish: 'diecisiete', translation: 'sedemnásť', pronunciation: 'dee-eh-see-see-EH-teh', example: 'Diecisiete páginas.', exampleTranslation: 'Sedemnásť strán.', category: 'numbers' },
            { spanish: 'dieciocho', translation: 'osemnásť', pronunciation: 'dee-eh-see-OH-choh', example: 'Dieciocho horas.', exampleTranslation: 'Osemnásť hodín.', category: 'numbers' },
            { spanish: 'diecinueve', translation: 'devätnásť', pronunciation: 'dee-eh-see-NWEH-beh', example: 'Diecinueve estudiantes.', exampleTranslation: 'Devätnásť študentov.', category: 'numbers' },
            { spanish: 'veinte', translation: 'dvadsať', pronunciation: 'VAYN-teh', example: 'Veinte minutos.', exampleTranslation: 'Dvadsať minút.', category: 'numbers' },
          ],
          exercises: [
            { type: 'translation', prompt: 'Prelož do španielčiny: dvadsať', correct: 'veinte', vocab: 'veinte', explanation: 'Veinte = dvadsať.' },
            { type: 'multiple_choice', prompt: 'Aké číslo je "quince"?', options: ['15', '14', '16', '13'], correct: '15', vocab: 'quince', explanation: 'Quince = pätnásť.' },
            { type: 'fill_blank', prompt: 'Doplň: catorce, quince, ___', correct: 'dieciséis', vocab: 'dieciséis', explanation: 'Po pätnástich (quince) nasleduje šestnásť (dieciséis).' },
            { type: 'multiple_choice', prompt: 'Množné číslo od "el número" je…', options: ['los números', 'las números', 'el números', 'la números'], correct: 'los números', grammar: 'plurals', explanation: 'Mužský rod v množnom čísle → "los números".' },
            { type: 'multiple_choice', prompt: 'Ktoré slovo končí v množnom čísle na -es?', options: ['ciudad', 'casa', 'número', 'mesa'], correct: 'ciudad', grammar: 'plurals', explanation: 'Slová končiace na spoluhlásku pridávajú -es: ciudad → ciudades.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: osemnásť', correct: 'dieciocho', vocab: 'dieciocho', explanation: 'Dieciocho = osemnásť.' },
            { type: 'multiple_choice', prompt: '"Diecisiete" je…', options: ['17', '16', '18', '19'], correct: '17', vocab: 'diecisiete', explanation: 'Diecisiete = sedemnásť.' },
            { type: 'fill_blank', prompt: 'Doplň: once, doce, ___, catorce', correct: 'trece', vocab: 'trece', explanation: 'Po dvanástich (doce) nasleduje trinásť (trece).' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Quince minutos.', 'Catorce minutos.', 'Diez minutos.', 'Veinte minutos.'], correct: 'Quince minutos.', audioText: 'Quince minutos.', vocab: 'quince', explanation: 'Počul si "Quince minutos" — pätnásť minút.' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['Doce meses.', 'Trece meses.', 'Once meses.', 'Veinte meses.'], correct: 'Doce meses.', audioText: 'Doce meses.', vocab: 'doce', explanation: 'Počul si "Doce meses" — dvanásť mesiacov.' },
            { type: 'speaking', prompt: 'Zopakuj po španielsky: Dvadsať minút.', audioText: 'Veinte minutos.', correct: 'Veinte minutos.', vocab: 'veinte', hint: 'Povedz "Veinte minutos".' },
          ],
        },
      ],
    },
    {
      slug: 'at-home',
      title: 'Doma',
      description: 'Opíš svoj dom a používaj farby.',
      lessons: [
        {
          title: 'Môj dom',
          description: 'Nauč sa slová pre izby a veci v dome.',
          day: 10,
          minutes: 30,
          grammar: {
            slug: 'hay',
            title: 'Hay: je / sú',
            explanation:
              '"Hay" sa používa, keď hovoríme o existencii niečoho — či už je jedna vec (je) alebo viac vecí (sú). Nemení sa podľa čísla.',
            rule: 'hay + člen/číslovka + podstatné meno: Hay una mesa. Hay dos sillas. Otázka: ¿Hay un baño? Negácia: No hay.',
            examples: [
              { spanish: 'En mi casa hay una mesa.', translation: 'V mojom dome je stôl.' },
              { spanish: 'No hay sillas.', translation: 'Nie sú tam stoličky.' },
              { spanish: '¿Hay un baño?', translation: 'Je tam kúpeľňa?' },
            ],
          },
          vocab: [
            { spanish: 'casa', translation: 'dom', pronunciation: 'KAH-sah', example: 'Mi casa es pequeña.', exampleTranslation: 'Môj dom je malý.', category: 'home' },
            { spanish: 'mesa', translation: 'stôl', pronunciation: 'MEH-sah', example: 'Hay una mesa en el salón.', exampleTranslation: 'V obývačke je stôl.', category: 'home' },
            { spanish: 'silla', translation: 'stolička', pronunciation: 'SEE-yah', example: 'Hay cuatro sillas.', exampleTranslation: 'Sú tam štyri stoličky.', category: 'home' },
            { spanish: 'cama', translation: 'posteľ', pronunciation: 'KAH-mah', example: 'Mi cama es grande.', exampleTranslation: 'Moja posteľ je veľká.', category: 'home' },
            { spanish: 'puerta', translation: 'dvere', pronunciation: 'PWEHR-tah', example: 'La puerta está abierta.', exampleTranslation: 'Dvere sú otvorené.', category: 'home' },
            { spanish: 'ventana', translation: 'okno', pronunciation: 'ben-TAH-nah', example: 'La ventana es pequeña.', exampleTranslation: 'Okno je malé.', category: 'home' },
            { spanish: 'cocina', translation: 'kuchyňa', pronunciation: 'koh-SEE-nah', example: 'La cocina está limpia.', exampleTranslation: 'Kuchyňa je čistá.', category: 'home' },
            { spanish: 'baño', translation: 'kúpeľňa', pronunciation: 'BAH-nyoh', example: '¿Dónde está el baño?', exampleTranslation: 'Kde je kúpeľňa?', category: 'home' },
            { spanish: 'salón', translation: 'obývačka', pronunciation: 'sah-LON', example: 'El salón es muy amplio.', exampleTranslation: 'Obývačka je veľmi priestranná.', category: 'home' },
            { spanish: 'habitación', translation: 'izba', pronunciation: 'ah-bee-tah-see-ON', example: 'Mi habitación es blanca.', exampleTranslation: 'Moja izba je biela.', category: 'home' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieme "dom"?', options: ['casa', 'cama', 'mesa', 'silla'], correct: 'casa', vocab: 'casa', explanation: '"Casa" = dom.' },
            { type: 'fill_blank', prompt: 'Doplň: ¿___ (je tam) un baño?', correct: 'Hay', vocab: 'casa', explanation: '"¿Hay un baño?" = Je tam kúpeľňa?' },
            { type: 'multiple_choice', prompt: '"Hay dos sillas" znamená…', options: ['Sú tam dve stoličky', 'Je tam jedna stolička', 'Nie sú tam stoličky', 'Kúp dve stoličky'], correct: 'Sú tam dve stoličky', grammar: 'hay', explanation: '"Hay" = je/sú; "dos sillas" = dve stoličky.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: posteľ', correct: 'cama', vocab: 'cama', explanation: '"Cama" = posteľ.' },
            { type: 'multiple_choice', prompt: 'Ktoré slovo znamená "kuchyňa"?', options: ['cocina', 'baño', 'salón', 'puerta'], correct: 'cocina', vocab: 'cocina', explanation: '"Cocina" = kuchyňa.' },
            { type: 'fill_blank', prompt: 'Doplň: No ___ (nie je tam) sillas.', correct: 'hay', grammar: 'hay', explanation: 'Negácia s "hay" je "no hay".' },
            { type: 'multiple_choice', prompt: 'Kde je kúpeľňa? → ¿Dónde está el ___?', options: ['baño', 'salón', 'cocina', 'mesa'], correct: 'baño', vocab: 'baño', explanation: '"El baño" = kúpeľňa.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: okno', correct: 'ventana', vocab: 'ventana', explanation: '"Ventana" = okno.' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['En mi casa hay una mesa.', 'En mi casa hay dos mesas.', 'En mi casa hay una cama.', 'No hay una mesa.'], correct: 'En mi casa hay una mesa.', audioText: 'En mi casa hay una mesa.', vocab: 'mesa', explanation: 'Počul si "En mi casa hay una mesa" — v mojom dome je stôl.' },
            { type: 'listening', prompt: 'Vypočuj si vetu a vyber, čo si počul.', options: ['No hay sillas.', 'Hay dos sillas.', 'Hay una silla.', 'No hay mesas.'], correct: 'No hay sillas.', audioText: 'No hay sillas.', vocab: 'silla', explanation: 'Počul si "No hay sillas" — nie sú tam stoličky.' },
            { type: 'speaking', prompt: 'Zopakuj po španielsky: Kde je kúpeľňa?', audioText: '¿Dónde está el baño?', correct: '¿Dónde está el baño?', vocab: 'baño', hint: 'Povedz "¿Dónde está el baño?"' },
          ],
        },
        {
          title: 'Farby',
          description: 'Nauč sa farby a opisuj nimi veci doma.',
          day: 11,
          minutes: 30,
          grammar: {
            slug: 'colors_agreement',
            title: 'Farby a zhoda',
            explanation:
              'Farby sú prídavné mená, preto sa menia podľa rodu a čísla podstatného mena. "Rojo" (červený) sa v ženskom rode mení na "roja". "Azul" a "verde" sa nemenia.',
            rule: 'rojo/roja, blanco/blanca, negro/negra, amarillo/amarilla · azul, verde (bez zmeny). Otázka: ¿De qué color es…?',
            examples: [
              { spanish: 'La casa es blanca.', translation: 'Dom je biely.' },
              { spanish: 'El coche es rojo.', translation: 'Auto je červené.' },
              { spanish: '¿De qué color es tu habitación?', translation: 'Akej farby je tvoja izba?' },
            ],
          },
          vocab: [
            { spanish: 'rojo', translation: 'červený', pronunciation: 'ROH-hoh', example: 'El libro es rojo.', exampleTranslation: 'Kniha je červená.', category: 'colors' },
            { spanish: 'azul', translation: 'modrý', pronunciation: 'ah-SOOL', example: 'El cielo es azul.', exampleTranslation: 'Obloha je modrá.', category: 'colors' },
            { spanish: 'verde', translation: 'zelený', pronunciation: 'BEHR-deh', example: 'La mesa es verde.', exampleTranslation: 'Stôl je zelený.', category: 'colors' },
            { spanish: 'amarillo', translation: 'žltý', pronunciation: 'ah-mah-REE-yoh', example: 'El sol es amarillo.', exampleTranslation: 'Slnko je žlté.', category: 'colors' },
            { spanish: 'negro', translation: 'čierny', pronunciation: 'NEH-groh', example: 'El gato es negro.', exampleTranslation: 'Mačka je čierna.', category: 'colors' },
            { spanish: 'blanco', translation: 'biely', pronunciation: 'BLAHN-koh', example: 'La pared es blanca.', exampleTranslation: 'Stena je biela.', category: 'colors' },
            { spanish: 'gris', translation: 'sivý', pronunciation: 'GREES', example: 'El coche es gris.', exampleTranslation: 'Auto je sivé.', category: 'colors' },
            { spanish: 'marrón', translation: 'hnedý', pronunciation: 'mah-RRON', example: 'La silla es marrón.', exampleTranslation: 'Stolička je hnedá.', category: 'colors' },
            { spanish: 'color', translation: 'farba', pronunciation: 'koh-LOR', example: '¿De qué color es?', exampleTranslation: 'Akej je to farby?', category: 'colors' },
            { spanish: '¿de qué color?', translation: 'akej farby?', pronunciation: 'deh KEH koh-LOR', example: '¿De qué color es tu casa?', exampleTranslation: 'Akej farby je tvoj dom?', category: 'colors' },
          ],
          exercises: [
            { type: 'translation', prompt: 'Prelož do španielčiny: modrý', correct: 'azul', vocab: 'azul', explanation: '"Azul" = modrý.' },
            { type: 'multiple_choice', prompt: 'Ženský tvar od "rojo" je…', options: ['roja', 'rojo', 'rojos', 'rojas'], correct: 'roja', grammar: 'colors_agreement', explanation: '-o → -a pre ženský rod: rojo → roja.' },
            { type: 'multiple_choice', prompt: '"La pared es blanca" znamená…', options: ['Stena je biela', 'Stena je čierna', 'Dvere sú biele', 'Dom je biely'], correct: 'Stena je biela', grammar: 'colors_agreement', explanation: '"La pared" (stena) + "blanca" (biela).' },
            { type: 'fill_blank', prompt: 'Doplň: El coche es ___. (červený)', correct: 'rojo', vocab: 'rojo', explanation: '"El coche" (auto, m. r.) → "rojo".' },
            { type: 'multiple_choice', prompt: 'Ktorá farba sa nemení podľa rodu?', options: ['verde', 'rojo', 'blanco', 'negro'], correct: 'verde', grammar: 'colors_agreement', explanation: '"Verde" a "azul" sú rovnaké pre oba rody.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: farba', correct: 'color', vocab: 'color', explanation: '"Color" = farba.' },
            { type: 'multiple_choice', prompt: 'Akej farby je slnko (el sol)?', options: ['amarillo', 'azul', 'negro', 'verde'], correct: 'amarillo', vocab: 'amarillo', explanation: 'Slnko je zvyčajne žlté → "amarillo".' },
            { type: 'multiple_choice', prompt: 'Ako sa opýtaš "akej farby?"', options: ['¿De qué color?', '¿Cuánto cuesta?', '¿Dónde está?', '¿Cómo estás?'], correct: '¿De qué color?', vocab: '¿de qué color?', explanation: '"¿De qué color?" sa pýta na farbu.' },
          ],
        },
      ],
    },
    {
      slug: 'food-drink',
      title: 'Jedlo a nápoje',
      description: 'Objednaj si jedlo a nápoje.',
      lessons: [
        {
          title: 'Jedlo a nápoje',
          description: 'Nauč sa slová pre jedlo a nápoje.',
          day: 12,
          minutes: 30,
          grammar: {
            slug: 'querer',
            title: 'Querer: chcieť',
            explanation:
              'Sloveso "querer" (chcieť) je veľmi užitočné v kaviarni a obchode. Používa sa aj pre ľudí ("Te quiero" = mám ťa rád), ale najprv sa nauč "chcieť" pre veci.',
            rule: 'yo quiero, tú quieres, él/ella quiere. quiero + podstatné meno: Quiero un café. Otázka: ¿Qué quieres?',
            examples: [
              { spanish: 'Quiero un café.', translation: 'Chcem kávu.' },
              { spanish: '¿Qué quieres?', translation: 'Čo chceš?' },
              { spanish: 'Ella quiere agua.', translation: 'Ona chce vodu.' },
            ],
          },
          vocab: [
            { spanish: 'comida', translation: 'jedlo', pronunciation: 'koh-MEE-dah', example: 'La comida es buena.', exampleTranslation: 'Jedlo je dobré.', category: 'food' },
            { spanish: 'agua', translation: 'voda', pronunciation: 'AH-gwah', example: 'Quiero agua, por favor.', exampleTranslation: 'Chcem vodu, prosím.', category: 'drinks' },
            { spanish: 'café', translation: 'káva', pronunciation: 'kah-FEH', example: 'Un café con leche.', exampleTranslation: 'Kávu s mliekom.', category: 'drinks' },
            { spanish: 'té', translation: 'čaj', pronunciation: 'TEH', example: 'Quiero un té.', exampleTranslation: 'Chcem čaj.', category: 'drinks' },
            { spanish: 'pan', translation: 'chlieb', pronunciation: 'PAN', example: 'Pan fresco, por favor.', exampleTranslation: 'Čerstvý chlieb, prosím.', category: 'food' },
            { spanish: 'queso', translation: 'syr', pronunciation: 'KEH-soh', example: 'Me gusta el queso.', exampleTranslation: 'Mám rád syr.', category: 'food' },
            { spanish: 'carne', translation: 'mäso', pronunciation: 'KAR-neh', example: 'Quiero carne.', exampleTranslation: 'Chcem mäso.', category: 'food' },
            { spanish: 'pollo', translation: 'kura', pronunciation: 'POH-yoh', example: 'Pollo con patatas.', exampleTranslation: 'Kura so zemiakmi.', category: 'food' },
            { spanish: 'pescado', translation: 'ryba', pronunciation: 'pes-KAH-doh', example: 'El pescado está rico.', exampleTranslation: 'Ryba je výborná.', category: 'food' },
            { spanish: 'fruta', translation: 'ovocie', pronunciation: 'FROO-tah', example: 'La fruta es saludable.', exampleTranslation: 'Ovocie je zdravé.', category: 'food' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieme "voda"?', options: ['agua', 'café', 'té', 'pan'], correct: 'agua', vocab: 'agua', explanation: '"Agua" = voda.' },
            { type: 'fill_blank', prompt: 'Doplň: ___ (chcem) un café.', correct: 'Quiero', vocab: 'café', explanation: 'Prvý tvar "querer" pre "ja" je "quiero".' },
            { type: 'translation', prompt: 'Prelož do španielčiny: jedlo', correct: 'comida', vocab: 'comida', explanation: '"Comida" = jedlo.' },
            { type: 'multiple_choice', prompt: 'Ella ___ agua. (chce)', options: ['quiere', 'quiero', 'quieres', 'quieren'], correct: 'quiere', grammar: 'querer', explanation: 'S "ella" používame "quiere".' },
            { type: 'fill_blank', prompt: 'Doplň: ¿Qué ___? (chceš — ty)', correct: 'quieres', grammar: 'querer', explanation: 'S "tú" používame "quieres".' },
            { type: 'multiple_choice', prompt: 'Ktoré znamená "chlieb"?', options: ['pan', 'queso', 'carne', 'pollo'], correct: 'pan', vocab: 'pan', explanation: '"Pan" = chlieb.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: ovocie', correct: 'fruta', vocab: 'fruta', explanation: '"Fruta" = ovocie.' },
            { type: 'multiple_choice', prompt: '"Quiero un té" znamená…', options: ['Chcem čaj', 'Chcem kávu', 'Chcem vodu', 'Nemám rád čaj'], correct: 'Chcem čaj', vocab: 'té', explanation: '"Quiero un té" = chcem čaj.' },
          ],
        },
        {
          title: 'V reštaurácii',
          description: 'Objednaj si jedlo v reštaurácii a povedz, čo potrebuješ.',
          day: 13,
          minutes: 30,
          grammar: {
            slug: 'tener',
            title: 'Tener: mať',
            explanation:
              'Sloveso "tener" (mať) používame na vlastníctvo a na pocity a potreby: "tengo hambre" (mám hlad), "tengo sed" (mám smäd).',
            rule: 'yo tengo, tú tienes, él/ella tiene. Tengo hambre = mám hlad · Tengo sed = mám smäd · ¿Tienes hambre?',
            examples: [
              { spanish: 'Tengo hambre.', translation: 'Mám hlad.' },
              { spanish: '¿Tienes sed?', translation: 'Máš smäd?' },
              { spanish: 'Tengo dos botellas.', translation: 'Mám dve fľaše.' },
            ],
          },
          vocab: [
            { spanish: 'camarero', translation: 'čašník', pronunciation: 'kah-mah-REH-roh', example: '¡Camarero, por favor!', exampleTranslation: 'Čašník, prosím!', category: 'restaurant' },
            { spanish: 'menú', translation: 'jedálny lístok', pronunciation: 'meh-NOO', example: '¿Me traes el menú?', exampleTranslation: 'Prinesieš mi jedálny lístok?', category: 'restaurant' },
            { spanish: 'cuenta', translation: 'účet', pronunciation: 'KWEN-tah', example: 'La cuenta, por favor.', exampleTranslation: 'Účet, prosím.', category: 'restaurant' },
            { spanish: 'hambre', translation: 'hlad', pronunciation: 'AHM-breh', example: 'Tengo mucha hambre.', exampleTranslation: 'Mám veľký hlad.', category: 'feelings' },
            { spanish: 'sed', translation: 'smäd', pronunciation: 'SED', example: 'Tengo sed.', exampleTranslation: 'Mám smäd.', category: 'feelings' },
            { spanish: 'botella', translation: 'fľaša', pronunciation: 'boh-TEH-yah', example: 'Una botella de agua.', exampleTranslation: 'Fľašu vody.', category: 'restaurant' },
            { spanish: 'vaso', translation: 'pohár', pronunciation: 'BAH-soh', example: 'Un vaso de vino.', exampleTranslation: 'Pohár vína.', category: 'restaurant' },
            { spanish: 'taza', translation: 'šálka', pronunciation: 'TAH-sah', example: 'Una taza de café.', exampleTranslation: 'Šálku kávy.', category: 'restaurant' },
            { spanish: 'plato', translation: 'tanier', pronunciation: 'PLAH-toh', example: 'Un plato de sopa.', exampleTranslation: 'Tanier polievky.', category: 'restaurant' },
            { spanish: 'tenedor', translation: 'vidlička', pronunciation: 'teh-neh-DOR', example: '¿Dónde está el tenedor?', exampleTranslation: 'Kde je vidlička?', category: 'restaurant' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieme "mám hlad"?', options: ['Tengo hambre', 'Tengo sed', 'Quiero café', 'Estoy bien'], correct: 'Tengo hambre', vocab: 'hambre', explanation: '"Tengo hambre" = mám hlad.' },
            { type: 'fill_blank', prompt: 'Doplň: Tengo ___. (smäd)', correct: 'sed', vocab: 'sed', explanation: '"Tener sed" = mať smäd.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: účet, prosím', correct: 'La cuenta, por favor', vocab: 'cuenta', explanation: '"La cuenta, por favor" si vypýtaš v reštaurácii.' },
            { type: 'multiple_choice', prompt: 'Ella ___ hambre. (má)', options: ['tiene', 'tengo', 'tienes', 'tienen'], correct: 'tiene', grammar: 'tener', explanation: 'S "ella" používame "tiene".' },
            { type: 'multiple_choice', prompt: '"Una taza de café" je…', options: ['šálka kávy', 'pohár vody', 'fľaša piva', 'tanier polievky'], correct: 'šálka kávy', vocab: 'taza', explanation: '"Taza" = šálka.' },
            { type: 'multiple_choice', prompt: 'Kto ti prinesie jedálny lístok?', options: ['camarero', 'coche', 'puerta', 'silla'], correct: 'camarero', vocab: 'camarero', explanation: '"El camarero" je čašník.' },
            { type: 'fill_blank', prompt: 'Doplň: Una ___ (fľaša) de agua.', correct: 'botella', vocab: 'botella', explanation: '"Botella" = fľaša.' },
            { type: 'multiple_choice', prompt: '"¿Tienes sed?" znamená…', options: ['Máš smäd?', 'Máš hlad?', 'Máš čas?', 'Máš peniaze?'], correct: 'Máš smäd?', grammar: 'tener', explanation: '"¿Tienes sed?" = máš smäd?' },
          ],
        },
      ],
    },
    {
      slug: 'around-town',
      title: 'Po meste',
      description: 'Nájdi cestu po meste a opýtaj sa na smer.',
      lessons: [
        {
          title: 'Miesta v meste',
          description: 'Nauč sa názvy miest a používaj "estar".',
          day: 14,
          minutes: 30,
          grammar: {
            slug: 'estar_locations',
            title: 'Estar: byť (miesto)',
            explanation:
              '"Estar" sa používa na miesto a aktuálny stav — na rozdiel od "ser", ktoré opisuje identitu. "El banco está cerca" (Banka je blízko).',
            rule: 'yo estoy, tú estás, él/ella está. Estoy en el centro. El parque está cerca.',
            examples: [
              { spanish: 'El banco está aquí.', translation: 'Banka je tu.' },
              { spanish: 'Estoy en el centro.', translation: 'Som v centre.' },
              { spanish: 'El parque está cerca.', translation: 'Park je blízko.' },
            ],
          },
          vocab: [
            { spanish: 'ciudad', translation: 'mesto', pronunciation: 'see-oo-DAD', example: 'Vivo en la ciudad.', exampleTranslation: 'Bývam v meste.', category: 'city' },
            { spanish: 'centro', translation: 'centrum', pronunciation: 'SEN-troh', example: 'El centro está lejos.', exampleTranslation: 'Centrum je ďaleko.', category: 'city' },
            { spanish: 'banco', translation: 'banka', pronunciation: 'BAHN-koh', example: '¿Dónde está el banco?', exampleTranslation: 'Kde je banka?', category: 'places' },
            { spanish: 'hospital', translation: 'nemocnica', pronunciation: 'os-pee-TAL', example: 'El hospital está cerca.', exampleTranslation: 'Nemocnica je blízko.', category: 'places' },
            { spanish: 'escuela', translation: 'škola', pronunciation: 'es-KWEH-lah', example: 'Mi hija va a la escuela.', exampleTranslation: 'Moja dcéra chodí do školy.', category: 'places' },
            { spanish: 'parque', translation: 'park', pronunciation: 'PAR-keh', example: 'Los niños juegan en el parque.', exampleTranslation: 'Deti sa hrajú v parku.', category: 'places' },
            { spanish: 'iglesia', translation: 'kostol', pronunciation: 'ee-GLEH-see-ah', example: 'La iglesia es antigua.', exampleTranslation: 'Kostol je starý.', category: 'places' },
            { spanish: 'tienda', translation: 'obchod', pronunciation: 'tee-EN-dah', example: 'La tienda está abierta.', exampleTranslation: 'Obchod je otvorený.', category: 'places' },
            { spanish: 'supermercado', translation: 'supermarket', pronunciation: 'soo-per-mer-KAH-doh', example: 'Voy al supermercado.', exampleTranslation: 'Idem do supermarketu.', category: 'places' },
            { spanish: 'farmacia', translation: 'lekáreň', pronunciation: 'far-MAH-see-ah', example: '¿Hay una farmacia aquí?', exampleTranslation: 'Je tu lekáreň?', category: 'places' },
          ],
          exercises: [
            { type: 'translation', prompt: 'Prelož do španielčiny: mesto', correct: 'ciudad', vocab: 'ciudad', explanation: '"Ciudad" = mesto.' },
            { type: 'multiple_choice', prompt: 'Kde kúpiš lieky? → la ___', options: ['farmacia', 'escuela', 'iglesia', 'banco'], correct: 'farmacia', vocab: 'farmacia', explanation: '"La farmacia" = lekáreň.' },
            { type: 'multiple_choice', prompt: 'El banco ___ cerca. (je)', options: ['está', 'es', 'son', 'estás'], correct: 'está', grammar: 'estar_locations', explanation: 'Miesto s "estar": el banco está.' },
            { type: 'fill_blank', prompt: 'Doplň: Yo ___ en el centro. (som)', correct: 'estoy', grammar: 'estar_locations', explanation: 'S "yo" pri "estar" → "estoy".' },
            { type: 'multiple_choice', prompt: 'Ktoré znamená "nemocnica"?', options: ['hospital', 'parque', 'tienda', 'centro'], correct: 'hospital', vocab: 'hospital', explanation: '"El hospital" = nemocnica.' },
            { type: 'multiple_choice', prompt: '"Estoy en el parque" znamená…', options: ['Som v parku', 'Idem do parku', 'Mám rád park', 'Park je blízko'], correct: 'Som v parku', grammar: 'estar_locations', explanation: '"Estoy en el parque" = som v parku.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: supermarket', correct: 'supermercado', vocab: 'supermercado', explanation: '"Supermercado" = supermarket.' },
            { type: 'multiple_choice', prompt: 'Ktoré miesto je na to, aby si si požičal peniaze?', options: ['banco', 'iglesia', 'parque', 'escuela'], correct: 'banco', vocab: 'banco', explanation: '"El banco" je banka.' },
          ],
        },
        {
          title: 'Kde je…?',
          description: 'Opýtaj sa na smer a rozumej odpovediam.',
          day: 15,
          minutes: 30,
          grammar: {
            slug: 'donde_prepositions',
            title: '¿Dónde está? + predložky',
            explanation:
              'Otázka "¿Dónde está…?" (Kde je?) a odpoveď s predložkami: "cerca" (blízko), "lejos" (ďaleko), "a la izquierda" (vľavo), "a la derecha" (vpravo), "enfrente" (naproti).',
            rule: '¿Dónde está el banco? → Está cerca. / Está a la derecha. · cerca de (blízko od), lejos de (ďaleko od), al lado de (vedľa).',
            examples: [
              { spanish: '¿Dónde está la farmacia?', translation: 'Kde je lekáreň?' },
              { spanish: 'Está cerca del parque.', translation: 'Je blízko parku.' },
              { spanish: 'El banco está a la derecha.', translation: 'Banka je vpravo.' },
            ],
          },
          vocab: [
            { spanish: '¿dónde?', translation: 'kde?', pronunciation: 'DON-deh', example: '¿Dónde está el hotel?', exampleTranslation: 'Kde je hotel?', category: 'directions' },
            { spanish: 'cerca', translation: 'blízko', pronunciation: 'SEHR-kah', example: 'La escuela está cerca.', exampleTranslation: 'Škola je blízko.', category: 'directions' },
            { spanish: 'lejos', translation: 'ďaleko', pronunciation: 'LEH-hos', example: 'El hospital está lejos.', exampleTranslation: 'Nemocnica je ďaleko.', category: 'directions' },
            { spanish: 'izquierda', translation: 'ľavá strana', pronunciation: 'ees-kee-EHR-dah', example: 'Gira a la izquierda.', exampleTranslation: 'Odboč doľava.', category: 'directions' },
            { spanish: 'derecha', translation: 'pravá strana', pronunciation: 'deh-REH-chah', example: 'El banco está a la derecha.', exampleTranslation: 'Banka je vpravo.', category: 'directions' },
            { spanish: 'recto', translation: 'rovno', pronunciation: 'REK-toh', example: 'Sigue recto.', exampleTranslation: 'Choď rovno.', category: 'directions' },
            { spanish: 'enfrente', translation: 'naproti', pronunciation: 'en-FREN-teh', example: 'La tienda está enfrente.', exampleTranslation: 'Obchod je naproti.', category: 'directions' },
            { spanish: 'al lado', translation: 'vedľa', pronunciation: 'al LAH-doh', example: 'Está al lado del parque.', exampleTranslation: 'Je vedľa parku.', category: 'directions' },
            { spanish: 'aquí', translation: 'tu', pronunciation: 'ah-KEE', example: 'Está aquí.', exampleTranslation: 'Je tu.', category: 'directions' },
            { spanish: 'allí', translation: 'tam', pronunciation: 'ah-YEE', example: 'La farmacia está allí.', exampleTranslation: 'Lekáreň je tam.', category: 'directions' },
          ],
          exercises: [
            { type: 'translation', prompt: 'Prelož do španielčiny: kde?', correct: '¿dónde?', vocab: '¿dónde?', explanation: '"¿Dónde?" = kde?' },
            { type: 'multiple_choice', prompt: 'Ako povieš "vpravo"?', options: ['a la derecha', 'a la izquierda', 'recto', 'lejos'], correct: 'a la derecha', vocab: 'derecha', explanation: '"A la derecha" = vpravo.' },
            { type: 'multiple_choice', prompt: 'El parque está ___ de la escuela. (vedľa)', options: ['al lado', 'lejos', 'recto', 'aquí'], correct: 'al lado', vocab: 'al lado', explanation: '"Al lado de" = vedľa.' },
            { type: 'fill_blank', prompt: 'Doplň: La farmacia está ___ (tam).', correct: 'allí', vocab: 'allí', explanation: '"Allí" = tam.' },
            { type: 'multiple_choice', prompt: '"Sigue recto" znamená…', options: ['Choď rovno', 'Odboč vľavo', 'Je ďaleko', 'Zastav'], correct: 'Choď rovno', vocab: 'recto', explanation: '"Sigue recto" = choď rovno.' },
            { type: 'fill_blank', prompt: 'Doplň: Está ___ (blízko).', correct: 'cerca', vocab: 'cerca', explanation: '"Cerca" = blízko.' },
            { type: 'multiple_choice', prompt: 'El banco está a la izquierda. Banka je…', options: ['vľavo', 'vpravo', 'naproti', 'ďaleko'], correct: 'vľavo', vocab: 'izquierda', explanation: '"A la izquierda" = vľavo.' },
            { type: 'multiple_choice', prompt: 'Ako sa opýtaš "kde je banka?"', options: ['¿Dónde está el banco?', '¿Cuánto cuesta el banco?', '¿Qué hora es?', '¿De qué color es?'], correct: '¿Dónde está el banco?', vocab: '¿dónde?', explanation: '"¿Dónde está…?" = kde je?' },
            { type: 'multiple_choice', prompt: 'El banco está ___ de la escuela. (blízko)', options: ['cerca', 'lejos', 'recto', 'allí'], correct: 'cerca', grammar: 'donde_prepositions', explanation: '"Está cerca de…" = je blízko.' },
          ],
        },
      ],
    },
    {
      slug: 'shopping',
      title: 'Nakupovanie',
      description: 'Pýtaj sa na cenu a nakupuj.',
      lessons: [
        {
          title: 'V obchode',
          description: 'Opýtaj sa, koľko niečo stojí, a nakupuj.',
          day: 16,
          minutes: 30,
          grammar: {
            slug: 'costar',
            title: 'Costar: stáť (cena)',
            explanation:
              'Sloveso "costar" (stáť) na otázku o cene: "¿Cuánto cuesta?" (koľko to stojí?) a "¿Cuánto cuestan?" (koľko stoja?).',
            rule: 'cuesta (jednotné) / cuestan (množné). ¿Cuánto cuesta? → Cuesta cinco euros. Často pridáme "por favor".',
            examples: [
              { spanish: '¿Cuánto cuesta?', translation: 'Koľko to stojí?' },
              { spanish: 'Cuesta tres euros.', translation: 'Stojí to tri eurá.' },
              { spanish: '¿Cuánto cuestan las manzanas?', translation: 'Koľko stoja jablká?' },
            ],
          },
          vocab: [
            { spanish: 'dinero', translation: 'peniaze', pronunciation: 'dee-NEH-roh', example: 'No tengo dinero.', exampleTranslation: 'Nemám peniaze.', category: 'shopping' },
            { spanish: 'euro', translation: 'euro', pronunciation: 'EH-oo-roh', example: 'Cuesta dos euros.', exampleTranslation: 'Stojí to dve eurá.', category: 'shopping' },
            { spanish: 'precio', translation: 'cena', pronunciation: 'PREH-see-oh', example: '¿Cuál es el precio?', exampleTranslation: 'Aká je cena?', category: 'shopping' },
            { spanish: 'caro', translation: 'drahý', pronunciation: 'KAH-roh', example: 'Es muy caro.', exampleTranslation: 'Je to veľmi drahé.', category: 'shopping' },
            { spanish: 'barato', translation: 'lacný', pronunciation: 'bah-RAH-toh', example: 'Es barato.', exampleTranslation: 'Je to lacné.', category: 'shopping' },
            { spanish: '¿cuánto?', translation: 'koľko?', pronunciation: 'KWAHN-toh', example: '¿Cuánto cuesta?', exampleTranslation: 'Koľko to stojí?', category: 'shopping' },
            { spanish: 'pagar', translation: 'platiť', pronunciation: 'pah-GAR', example: 'Voy a pagar.', exampleTranslation: 'Idem platiť.', category: 'shopping' },
            { spanish: 'comprar', translation: 'kúpiť', pronunciation: 'kom-PRAR', example: 'Quiero comprar pan.', exampleTranslation: 'Chcem kúpiť chlieb.', category: 'shopping' },
            { spanish: 'vender', translation: 'predávať', pronunciation: 'ben-DER', example: 'Aquí venden fruta.', exampleTranslation: 'Tu predávajú ovocie.', category: 'shopping' },
            { spanish: 'rebaja', translation: 'zľava', pronunciation: 'reh-BAH-hah', example: 'Hay rebajas en la tienda.', exampleTranslation: 'V obchode sú zľavy.', category: 'shopping' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako sa opýtaš "koľko to stojí?"', options: ['¿Cuánto cuesta?', '¿Dónde está?', '¿Qué hora es?', '¿Cómo te llamas?'], correct: '¿Cuánto cuesta?', vocab: '¿cuánto?', explanation: '"¿Cuánto cuesta?" sa pýta na cenu.' },
            { type: 'fill_blank', prompt: 'Doplň: Cuesta cinco ___. (eurá)', correct: 'euros', vocab: 'euro', explanation: '"Euro" v množnom čísle → "euros".' },
            { type: 'multiple_choice', prompt: 'Množné číslo "cuestan" použiješ, keď…', options: ['veci sú viaceré', 'je jedna vec', 'niečo neexistuje', 'sa pýtaš na smer'], correct: 'veci sú viaceré', grammar: 'costar', explanation: '"Cuestan" pre množné číslo: ¿Cuánto cuestan las manzanas?' },
            { type: 'translation', prompt: 'Prelož do španielčiny: lacný', correct: 'barato', vocab: 'barato', explanation: '"Barato" = lacný; "caro" = drahý.' },
            { type: 'multiple_choice', prompt: '"Es muy caro" znamená…', options: ['Je to veľmi drahé', 'Je to lacné', 'Je to zadarmo', 'Nechcem to'], correct: 'Je to veľmi drahé', vocab: 'caro', explanation: '"Caro" = drahý.' },
            { type: 'multiple_choice', prompt: 'Ktoré sloveso znamená "platiť"?', options: ['pagar', 'comprar', 'vender', 'cambiar'], correct: 'pagar', vocab: 'pagar', explanation: '"Pagar" = platiť.' },
            { type: 'fill_blank', prompt: 'Doplň: Quiero ___ (kúpiť) pan.', correct: 'comprar', vocab: 'comprar', explanation: '"Comprar" = kúpiť.' },
            { type: 'multiple_choice', prompt: '"Hay rebajas" znamená…', options: ['Sú zľavy', 'Je draho', 'Je zavreté', 'Je tu málo ľudí'], correct: 'Sú zľavy', vocab: 'rebaja', explanation: '"Las rebajas" = zľavy.' },
          ],
        },
      ],
    },
  ],
};
