import type { SeedCourse } from './types.js';

export const A1_COURSE: SeedCourse = {
  cefrLevel: 'A1',
  name: 'Španielčina A1',
  modules: [
    {
      slug: 'daily-routine',
      title: 'Denná rutina',
      description: 'Povedz, koľko je hodín a čo robíš počas dňa.',
      lessons: [
        {
          title: 'Koľko je hodín?',
          description: 'Nauč sa určovať čas.',
          day: 17,
          minutes: 30,
          grammar: {
            slug: 'telling_time',
            title: 'Určovanie času',
            explanation:
              'Otázka "¿Qué hora es?" (Koľko je hodín?). Jedna hodina je "Es la una", dve a viac sú "Son las…". Polhodina je "y media", štvrťhodina "y cuarto".',
            rule: 'Es la una (jedna). Son las dos/tres… (dve, tri…). y media = a pol · y cuarto = a štvrť · De la mañana (ráno), de la tarde (popoludní), de la noche (večer).',
            examples: [
              { spanish: '¿Qué hora es? — Es la una.', translation: 'Koľko je hodín? — Je jedna.' },
              { spanish: 'Son las tres y media.', translation: 'Je tri a pol.' },
              { spanish: 'Son las ocho de la mañana.', translation: 'Je osem ráno.' },
            ],
          },
          vocab: [
            { spanish: 'hora', translation: 'hodina', pronunciation: 'OH-rah', example: '¿Qué hora es?', exampleTranslation: 'Koľko je hodín?', category: 'time' },
            { spanish: 'minuto', translation: 'minúta', pronunciation: 'mee-NOO-toh', example: 'Espera un minuto.', exampleTranslation: 'Počkaj minútu.', category: 'time' },
            { spanish: 'mañana', translation: 'ráno', pronunciation: 'mah-NYAH-nah', example: 'Son las siete de la mañana.', exampleTranslation: 'Je sedem ráno.', category: 'time' },
            { spanish: 'tarde', translation: 'popoludnie', pronunciation: 'TAR-deh', example: 'Son las cinco de la tarde.', exampleTranslation: 'Je päť popoludní.', category: 'time' },
            { spanish: 'noche', translation: 'večer / noc', pronunciation: 'NO-cheh', example: 'Son las diez de la noche.', exampleTranslation: 'Je desať večer.', category: 'time' },
            { spanish: 'ahora', translation: 'teraz', pronunciation: 'ah-OH-rah', example: 'Ahora son las dos.', exampleTranslation: 'Teraz sú dve.', category: 'time' },
            { spanish: 'temprano', translation: 'skoro', pronunciation: 'tem-PRAH-noh', example: 'Me levanto temprano.', exampleTranslation: 'Vstávam skoro.', category: 'time' },
            { spanish: 'media', translation: 'polovica', pronunciation: 'MEH-dee-ah', example: 'Son las tres y media.', exampleTranslation: 'Je tri a pol.', category: 'time' },
            { spanish: 'cuarto', translation: 'štvrť', pronunciation: 'KWAR-toh', example: 'Es la una y cuarto.', exampleTranslation: 'Je jedna a štvrť.', category: 'time' },
            { spanish: 'día', translation: 'deň', pronunciation: 'DEE-ah', example: 'Buen día.', exampleTranslation: 'Dobrý deň.', category: 'time' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako sa opýtaš "koľko je hodín?"', options: ['¿Qué hora es?', '¿Cuánto cuesta?', '¿Dónde está?', '¿De qué color?'], correct: '¿Qué hora es?', vocab: 'hora', explanation: '"¿Qué hora es?" = koľko je hodín?' },
            { type: 'multiple_choice', prompt: 'Pre jednu hodinu použiješ…', options: ['Es la una', 'Son las una', 'Es el uno', 'Son los uno'], correct: 'Es la una', grammar: 'telling_time', explanation: 'Jedna hodina → "Es la una".' },
            { type: 'fill_blank', prompt: 'Doplň: Son ___ dos. (je)', correct: 'las', grammar: 'telling_time', explanation: 'Dve a viac hodín → "Son las…".' },
            { type: 'multiple_choice', prompt: '"Son las tres y media" je…', options: ['tri a pol', 'tri a štvrť', 'štvrtá', 'tri ráno'], correct: 'tri a pol', vocab: 'media', explanation: '"Y media" = a pol.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: ráno', correct: 'mañana', vocab: 'mañana', explanation: '"Mañana" = ráno (aj zajtra).' },
            { type: 'fill_blank', prompt: 'Doplň: Son las cinco de la ___. (popoludní)', correct: 'tarde', vocab: 'tarde', explanation: '"De la tarde" = popoludní.' },
            { type: 'multiple_choice', prompt: '"Es la una y cuarto" je…', options: ['jedna a štvrť', 'jedna a pol', 'jedna', 'dve'], correct: 'jedna a štvrť', vocab: 'cuarto', explanation: '"Y cuarto" = a štvrť.' },
            { type: 'multiple_choice', prompt: 'Ktoré slovo znamená "deň"?', options: ['día', 'noche', 'hora', 'semana'], correct: 'día', vocab: 'día', explanation: '"El día" = deň.' },
          ],
        },
        {
          title: 'Môj deň',
          description: 'Hovor o tom, čo robíš počas dňa.',
          day: 18,
          minutes: 30,
          grammar: {
            slug: 'present_ar',
            title: 'Prítomný čas slovies na -ar',
            explanation:
              'Väčšina španielskych slovies končí na -ar. Kmeň + koncovky: -o, -as, -a, -amos, -áis, -an. Príklad: hablar → hablo, hablas, habla…',
            rule: 'yo hablo, tú hablas, él/ella habla, nosotros hablamos. Príklad: "Trabajo en la oficina" (Pracujem v kancelárii).',
            examples: [
              { spanish: 'Hablo español.', translation: 'Hovorím po španielsky.' },
              { spanish: 'Tú trabajas mucho.', translation: 'Ty veľa pracuješ.' },
              { spanish: 'Ella estudia inglés.', translation: 'Ona študuje angličtinu.' },
            ],
          },
          vocab: [
            { spanish: 'trabajar', translation: 'pracovať', pronunciation: 'trah-bah-HAR', example: 'Trabajo en una oficina.', exampleTranslation: 'Pracujem v kancelárii.', category: 'routine' },
            { spanish: 'estudiar', translation: 'študovať', pronunciation: 'es-too-dee-AR', example: 'Estudio español.', exampleTranslation: 'Študujem španielčinu.', category: 'routine' },
            { spanish: 'hablar', translation: 'hovoriť', pronunciation: 'ah-BLAR', example: 'Hablo tres idiomas.', exampleTranslation: 'Hovorím tromi jazykmi.', category: 'routine' },
            { spanish: 'escuchar', translation: 'počúvať', pronunciation: 'es-koo-CHAR', example: 'Escucho música.', exampleTranslation: 'Počúvam hudbu.', category: 'routine' },
            { spanish: 'mirar', translation: 'pozerať', pronunciation: 'mee-RAR', example: 'Miro la televisión.', exampleTranslation: 'Pozerám televíziu.', category: 'routine' },
            { spanish: 'cocinar', translation: 'variť', pronunciation: 'koh-see-NAR', example: 'Mi madre cocina muy bien.', exampleTranslation: 'Moja mama varí veľmi dobre.', category: 'routine' },
            { spanish: 'descansar', translation: 'odpočívať', pronunciation: 'des-kahn-SAR', example: 'Descanso los domingos.', exampleTranslation: 'V nedeľu odpočívam.', category: 'routine' },
            { spanish: 'pasear', translation: 'prechádzať sa', pronunciation: 'pah-seh-AR', example: 'Paseamos por el parque.', exampleTranslation: 'Prechádzame sa parkom.', category: 'routine' },
            { spanish: 'desayunar', translation: 'raňajkovať', pronunciation: 'deh-sah-yoo-NAR', example: 'Desayuno a las ocho.', exampleTranslation: 'Raňajkujem o ôsmej.', category: 'routine' },
            { spanish: 'cenar', translation: 'večerať', pronunciation: 'seh-NAR', example: 'Cenamos juntos.', exampleTranslation: 'Večeriame spolu.', category: 'routine' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieme "hovorím"?', options: ['hablo', 'hablas', 'habla', 'hablamos'], correct: 'hablo', grammar: 'present_ar', explanation: 'S "yo" → kmeň + -o: hablo.' },
            { type: 'fill_blank', prompt: 'Doplň: Tú ___ (pracuješ) mucho.', correct: 'trabajas', vocab: 'trabajar', explanation: 'S "tú" → kmeň + -as: trabajas.' },
            { type: 'multiple_choice', prompt: 'Ella ___ (študuje) inglés.', options: ['estudia', 'estudio', 'estudias', 'estudian'], correct: 'estudia', grammar: 'present_ar', explanation: 'S "ella" → kmeň + -a: estudia.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: variť', correct: 'cocinar', vocab: 'cocinar', explanation: '"Cocinar" = variť.' },
            { type: 'multiple_choice', prompt: 'Nosotros hablamos = …', options: ['my hovoríme', 'ty hovoríš', 'oni hovoria', 'ja hovorím'], correct: 'my hovoríme', grammar: 'present_ar', explanation: '"Nosotros hablamos" = my hovoríme.' },
            { type: 'fill_blank', prompt: 'Doplň: Yo ___ (počúvam) música.', correct: 'escucho', vocab: 'escuchar', explanation: 'S "yo" → escucho.' },
            { type: 'multiple_choice', prompt: 'Ktoré sloveso znamená "odpočívať"?', options: ['descansar', 'trabajar', 'estudiar', 'mirar'], correct: 'descansar', vocab: 'descansar', explanation: '"Descansar" = odpočívať.' },
            { type: 'multiple_choice', prompt: '"Desayuno a las ocho" znamená…', options: ['Raňajkujem o ôsmej', 'Večeriam o ôsmej', 'Vstávam o ôsmej', 'Pracujem do ôsmej'], correct: 'Raňajkujem o ôsmej', vocab: 'desayunar', explanation: '"Desayunar" = raňajkovať.' },
          ],
        },
      ],
    },
    {
      slug: 'free-time',
      title: 'Voľný čas',
      description: 'Hovor o tom, čo máš rád, a o počasí.',
      lessons: [
        {
          title: 'Mám rád…',
          description: 'Povedz, čo ťa baví, pomocou "gustar".',
          day: 19,
          minutes: 30,
          grammar: {
            slug: 'gustar',
            title: 'Gustar: mať rád',
            explanation:
              '"Gustar" doslova znamená "páči sa mi". "Me gusta" + jednotné číslo, "Me gustan" + množné číslo. Je to obrátene ako v slovenčine.',
            rule: 'Me gusta el café. Me gustan las manzanas. Otázka: ¿Te gusta…? Pre zdôraznenie: A mí me gusta.',
            examples: [
              { spanish: 'Me gusta la música.', translation: 'Mám rád hudbu.' },
              { spanish: 'Me gustan los libros.', translation: 'Mám rád knihy.' },
              { spanish: '¿Te gusta el cine?', translation: 'Máš rád kino?' },
            ],
          },
          vocab: [
            { spanish: 'música', translation: 'hudba', pronunciation: 'MOO-see-kah', example: 'Me gusta la música.', exampleTranslation: 'Mám rád hudbu.', category: 'hobbies' },
            { spanish: 'cine', translation: 'kino', pronunciation: 'SEE-neh', example: 'Vamos al cine.', exampleTranslation: 'Ideme do kina.', category: 'hobbies' },
            { spanish: 'libro', translation: 'kniha', pronunciation: 'LEE-broh', example: 'Leo un libro.', exampleTranslation: 'Čítam knihu.', category: 'hobbies' },
            { spanish: 'deporte', translation: 'šport', pronunciation: 'deh-POR-teh', example: 'El deporte es sano.', exampleTranslation: 'Šport je zdravý.', category: 'hobbies' },
            { spanish: 'fútbol', translation: 'futbal', pronunciation: 'FOOT-bol', example: 'Juego al fútbol.', exampleTranslation: 'Hrávam futbal.', category: 'hobbies' },
            { spanish: 'baile', translation: 'tanec', pronunciation: 'BAHY-leh', example: 'Me gusta el baile.', exampleTranslation: 'Mám rád tanec.', category: 'hobbies' },
            { spanish: 'viajar', translation: 'cestovať', pronunciation: 'bee-ah-HAR', example: 'Me encanta viajar.', exampleTranslation: 'Zbožňujem cestovať.', category: 'hobbies' },
            { spanish: 'leer', translation: 'čítať', pronunciation: 'leh-ER', example: 'Me gusta leer.', exampleTranslation: 'Rád čítam.', category: 'hobbies' },
            { spanish: 'escribir', translation: 'písať', pronunciation: 'es-kree-BEER', example: 'Escribo cada día.', exampleTranslation: 'Píšem každý deň.', category: 'hobbies' },
            { spanish: 'jugar', translation: 'hrať', pronunciation: 'hoo-GAR', example: 'Juego con mis amigos.', exampleTranslation: 'Hrávam sa s kamarátmi.', category: 'hobbies' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieš "mám rád hudbu"?', options: ['Me gusta la música', 'Me gustan la música', 'Me gusta música', 'Te gusta la música'], correct: 'Me gusta la música', grammar: 'gustar', explanation: '"Me gusta" + jednotné číslo: la música.' },
            { type: 'multiple_choice', prompt: 'Pre množné číslo použiješ…', options: ['Me gustan', 'Me gusta', 'Te gusta', 'Nos gusta'], correct: 'Me gustan', grammar: 'gustar', explanation: '"Me gustan los libros" — pri viacerých veciach "gustan".' },
            { type: 'fill_blank', prompt: 'Doplň: ¿Te ___ el cine?', correct: 'gusta', grammar: 'gustar', explanation: '"¿Te gusta el cine?" = máš rád kino?' },
            { type: 'translation', prompt: 'Prelož do španielčiny: hudba', correct: 'música', vocab: 'música', explanation: '"La música" = hudba.' },
            { type: 'multiple_choice', prompt: 'Ktoré sloveso znamená "cestovať"?', options: ['viajar', 'leer', 'jugar', 'escribir'], correct: 'viajar', vocab: 'viajar', explanation: '"Viajar" = cestovať.' },
            { type: 'multiple_choice', prompt: '"Me gustan los libros" znamená…', options: ['Mám rád knihy', 'Mám rád knihu', 'Nemám rád knihy', 'Kupujem knihy'], correct: 'Mám rád knihy', grammar: 'gustar', explanation: '"Los libros" (množné) → "me gustan".' },
            { type: 'fill_blank', prompt: 'Doplň: Me gusta el ___ (tanec).', correct: 'baile', vocab: 'baile', explanation: '"El baile" = tanec.' },
            { type: 'multiple_choice', prompt: 'Ktoré znamená "čítať"?', options: ['leer', 'escribir', 'mirar', 'escuchar'], correct: 'leer', vocab: 'leer', explanation: '"Leer" = čítať.' },
          ],
        },
        {
          title: 'Počasie',
          description: 'Hovor o počasí pomocou "hace".',
          day: 20,
          minutes: 30,
          grammar: {
            slug: 'weather',
            title: 'Hace + počasie',
            explanation:
              'Počasie sa v španielčine vyjadruje so slovesom "hacer": "hace calor" (je teplo), "hace frío" (je zima), "hace sol" (je slnečno). Dážď a sneh sú slovesá: "llueve" (prší), "nieva" (sneží).',
            rule: 'hace + podstatné meno: hace sol, hace calor, hace frío, hace viento. Slovesá: llueve (prší), nieva (sneží). Hace buen tiempo = je pekné počasie.',
            examples: [
              { spanish: 'Hoy hace calor.', translation: 'Dnes je teplo.' },
              { spanish: 'Mañana hace frío.', translation: 'Zajtra bude zima.' },
              { spanish: 'Hace mucho sol.', translation: 'Je veľmi slnečno.' },
            ],
          },
          vocab: [
            { spanish: 'sol', translation: 'slnko', pronunciation: 'SOL', example: 'Hace sol.', exampleTranslation: 'Je slnečno.', category: 'weather' },
            { spanish: 'lluvia', translation: 'dážď', pronunciation: 'YOO-bee-ah', example: 'Hay lluvia.', exampleTranslation: 'Prší.', category: 'weather' },
            { spanish: 'nieve', translation: 'sneh', pronunciation: 'nee-EH-beh', example: 'Hay nieve en la montaña.', exampleTranslation: 'Na horách je sneh.', category: 'weather' },
            { spanish: 'viento', translation: 'vietor', pronunciation: 'bee-EN-toh', example: 'Hace mucho viento.', exampleTranslation: 'Veľmi fúka.', category: 'weather' },
            { spanish: 'nube', translation: 'oblak', pronunciation: 'NOO-beh', example: 'Hay muchas nubes.', exampleTranslation: 'Je veľa oblakov.', category: 'weather' },
            { spanish: 'frío', translation: 'zima (chlad)', pronunciation: 'FREE-oh', example: 'Hace frío hoy.', exampleTranslation: 'Dnes je zima.', category: 'weather' },
            { spanish: 'calor', translation: 'teplo', pronunciation: 'kah-LOR', example: 'Hace calor en verano.', exampleTranslation: 'V lete je teplo.', category: 'weather' },
            { spanish: 'tiempo', translation: 'počasie', pronunciation: 'tee-EM-poh', example: '¿Qué tiempo hace?', exampleTranslation: 'Aké je počasie?', category: 'weather' },
            { spanish: 'hoy', translation: 'dnes', pronunciation: 'OY', example: 'Hoy hace sol.', exampleTranslation: 'Dnes je slnečno.', category: 'time' },
            { spanish: 'mañana', translation: 'zajtra', pronunciation: 'mah-NYAH-nah', example: 'Mañana llueve.', exampleTranslation: 'Zajtra bude pršať.', category: 'time' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieš "je slnečno"?', options: ['Hace sol', 'Hace lluvia', 'Hace nieve', 'Hace frío'], correct: 'Hace sol', grammar: 'weather', explanation: '"Hace sol" = je slnečno.' },
            { type: 'multiple_choice', prompt: '"Hace frío" znamená…', options: ['je zima', 'je teplo', 'prší', 'fúka'], correct: 'je zima', vocab: 'frío', explanation: '"Hace frío" = je zima.' },
            { type: 'fill_blank', prompt: 'Doplň: Hace ___ (teplo) en verano.', correct: 'calor', vocab: 'calor', explanation: '"Hace calor" = je teplo.' },
            { type: 'multiple_choice', prompt: 'Prší sa povie…', options: ['Llueve', 'Hace lluvia', 'Nieva', 'Está lluvia'], correct: 'Llueve', grammar: 'weather', explanation: 'Dážď je sloveso: "llueve" (prší).' },
            { type: 'translation', prompt: 'Prelož do španielčiny: sneh', correct: 'nieve', vocab: 'nieve', explanation: '"La nieve" = sneh; "nieva" = sneží.' },
            { type: 'multiple_choice', prompt: 'Hace mucho ___ (vietor).', options: ['viento', 'sol', 'frío', 'tiempo'], correct: 'viento', vocab: 'viento', explanation: '"Hace viento" = fúka.' },
            { type: 'fill_blank', prompt: 'Doplň: ¿Qué ___ hace? (počasie)', correct: 'tiempo', vocab: 'tiempo', explanation: '"¿Qué tiempo hace?" = aké je počasie?' },
            { type: 'multiple_choice', prompt: 'Ktoré znamená "dnes"?', options: ['hoy', 'mañana', 'ayer', 'noche'], correct: 'hoy', vocab: 'hoy', explanation: '"Hoy" = dnes.' },
          ],
        },
      ],
    },
    {
      slug: 'travel',
      title: 'Cestovanie',
      description: 'Zarezervuj si izbu a cestuj.',
      lessons: [
        {
          title: 'V hoteli',
          description: 'Zarezervuj si izbu a povedz, čo potrebuješ.',
          day: 21,
          minutes: 30,
          grammar: {
            slug: 'tener_necesitar',
            title: 'Tener + necesitar',
            explanation:
              '"Necesitar" (potrebovať) a "tener" (mať) ti v hoteli veľmi pomôžu: "Necesito una habitación" (potrebujem izbu), "¿Tiene una habitación libre?" (máte voľnú izbu?).',
            rule: 'necesito, necesitas, necesita · tengo, tienes, tiene. Necesito + podstatné meno. ¿Tiene usted…? (formálne).',
            examples: [
              { spanish: 'Necesito una habitación.', translation: 'Potrebujem izbu.' },
              { spanish: '¿Tiene una habitación libre?', translation: 'Máte voľnú izbu?' },
              { spanish: 'Tengo una reserva.', translation: 'Mám rezerváciu.' },
            ],
          },
          vocab: [
            { spanish: 'hotel', translation: 'hotel', pronunciation: 'oh-TEL', example: '¿Dónde está el hotel?', exampleTranslation: 'Kde je hotel?', category: 'travel' },
            { spanish: 'habitación', translation: 'izba', pronunciation: 'ah-bee-tah-see-ON', example: 'Necesito una habitación.', exampleTranslation: 'Potrebujem izbu.', category: 'travel' },
            { spanish: 'reserva', translation: 'rezervácia', pronunciation: 'reh-SEHR-bah', example: 'Tengo una reserva.', exampleTranslation: 'Mám rezerváciu.', category: 'travel' },
            { spanish: 'llave', translation: 'kľúč', pronunciation: 'YAH-beh', example: 'La llave de la habitación.', exampleTranslation: 'Kľúč od izby.', category: 'travel' },
            { spanish: 'recepción', translation: 'recepcia', pronunciation: 'reh-sep-see-ON', example: 'Está en la recepción.', exampleTranslation: 'Je na recepcii.', category: 'travel' },
            { spanish: 'equipaje', translation: 'batožina', pronunciation: 'eh-kee-PAH-heh', example: 'Mi equipaje está aquí.', exampleTranslation: 'Moja batožina je tu.', category: 'travel' },
            { spanish: 'pasaporte', translation: 'pas', pronunciation: 'pah-sah-POR-teh', example: '¿Tiene su pasaporte?', exampleTranslation: 'Máte pas?', category: 'travel' },
            { spanish: 'precio', translation: 'cena', pronunciation: 'PREH-see-oh', example: '¿Cuál es el precio por noche?', exampleTranslation: 'Aká je cena za noc?', category: 'travel' },
            { spanish: 'noche', translation: 'noc', pronunciation: 'NO-cheh', example: 'Dos noches, por favor.', exampleTranslation: 'Dve noci, prosím.', category: 'time' },
            { spanish: 'libre', translation: 'voľný', pronunciation: 'LEE-breh', example: '¿Hay una habitación libre?', exampleTranslation: 'Je voľná izba?', category: 'travel' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieš "potrebujem izbu"?', options: ['Necesito una habitación', 'Tengo una habitación', 'Quiero una habitación', 'Es una habitación'], correct: 'Necesito una habitación', grammar: 'tener_necesitar', explanation: '"Necesito" = potrebujem.' },
            { type: 'fill_blank', prompt: 'Doplň: Tengo una ___. (rezervácia)', correct: 'reserva', vocab: 'reserva', explanation: '"Tengo una reserva" = mám rezerváciu.' },
            { type: 'multiple_choice', prompt: '¿Tiene una habitación ___? (voľná)', options: ['libre', 'caro', 'grande', 'cerca'], correct: 'libre', vocab: 'libre', explanation: '"Libre" = voľný.' },
            { type: 'multiple_choice', prompt: 'Kto dostaneš na recepcii? → la ___', options: ['llave', 'cama', 'mesa', 'puerta'], correct: 'llave', vocab: 'llave', explanation: '"La llave" = kľúč.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: pas', correct: 'pasaporte', vocab: 'pasaporte', explanation: '"El pasaporte" = pas.' },
            { type: 'multiple_choice', prompt: 'Ella ___ (potrebuje) un taxi.', options: ['necesita', 'necesito', 'necesitas', 'necesitan'], correct: 'necesita', grammar: 'tener_necesitar', explanation: 'S "ella" → necesita.' },
            { type: 'multiple_choice', prompt: '"Mi equipaje está aquí" znamená…', options: ['Moja batožina je tu', 'Môj pas je tu', 'Moja izba je tu', 'Môj kľúč je tu'], correct: 'Moja batožina je tu', vocab: 'equipaje', explanation: '"El equipaje" = batožina.' },
            { type: 'fill_blank', prompt: 'Doplň: ¿Cuál es el ___ por noche? (cena)', correct: 'precio', vocab: 'precio', explanation: '"El precio" = cena.' },
          ],
        },
        {
          title: 'Cestovanie',
          description: 'Hovor o doprave a dopravných prostriedkoch.',
          day: 22,
          minutes: 30,
          grammar: {
            slug: 'ir_a',
            title: 'Ir + a: smer',
            explanation:
              'Sloveso "ir" (ísť) je nepravidelné: voy, vas, va, vamos… Smer vyjadríš pridaním "a" + miesto: "Voy a Madrid" (idem do Madridu).',
            rule: 'yo voy, tú vas, él/ella va, nosotros vamos. ir a + miesto: Voy a la estación. Otázka: ¿Adónde vas?',
            examples: [
              { spanish: 'Voy a Madrid.', translation: 'Idem do Madridu.' },
              { spanish: '¿Adónde vas?', translation: 'Kam ideš?' },
              { spanish: 'Vamos a la estación.', translation: 'Ideme na stanicu.' },
            ],
          },
          vocab: [
            { spanish: 'ir', translation: 'ísť', pronunciation: 'eer', example: 'Voy al aeropuerto.', exampleTranslation: 'Idem na letisko.', category: 'travel' },
            { spanish: 'avión', translation: 'lietadlo', pronunciation: 'ah-bee-ON', example: 'Vuelo en avión.', exampleTranslation: 'Letím lietadlom.', category: 'travel' },
            { spanish: 'tren', translation: 'vlak', pronunciation: 'TREN', example: 'El tren sale a las nueve.', exampleTranslation: 'Vlak odchádza o deviatej.', category: 'travel' },
            { spanish: 'autobús', translation: 'autobus', pronunciation: 'ow-toh-BOOS', example: 'El autobús es barato.', exampleTranslation: 'Autobus je lacný.', category: 'travel' },
            { spanish: 'coche', translation: 'auto', pronunciation: 'KOH-cheh', example: 'Voy en coche.', exampleTranslation: 'Idem autom.', category: 'travel' },
            { spanish: 'barco', translation: 'loď', pronunciation: 'BAR-koh', example: 'Viajamos en barco.', exampleTranslation: 'Cestujeme loďou.', category: 'travel' },
            { spanish: 'estación', translation: 'stanica', pronunciation: 'es-tah-see-ON', example: 'La estación está cerca.', exampleTranslation: 'Stanica je blízko.', category: 'travel' },
            { spanish: 'aeropuerto', translation: 'letisko', pronunciation: 'ah-eh-roh-PWEHR-toh', example: 'El aeropuerto está lejos.', exampleTranslation: 'Letisko je ďaleko.', category: 'travel' },
            { spanish: 'billete', translation: 'lístok', pronunciation: 'bee-YEH-teh', example: 'Un billete de tren.', exampleTranslation: 'Jeden vlakový lístok.', category: 'travel' },
            { spanish: 'maleta', translation: 'kufor', pronunciation: 'mah-LEH-tah', example: 'Mi maleta es grande.', exampleTranslation: 'Môj kufor je veľký.', category: 'travel' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieš "idem do Madridu"?', options: ['Voy a Madrid', 'Vas a Madrid', 'Va a Madrid', 'Vamos a Madrid'], correct: 'Voy a Madrid', grammar: 'ir_a', explanation: 'S "yo" pri "ir" → voy.' },
            { type: 'fill_blank', prompt: 'Doplň: ¿Adónde ___? (ideš)', correct: 'vas', grammar: 'ir_a', explanation: 'S "tú" → vas.' },
            { type: 'multiple_choice', prompt: 'Nosotros ___ a la playa. (ideme)', options: ['vamos', 'voy', 'vas', 'van'], correct: 'vamos', grammar: 'ir_a', explanation: 'S "nosotros" → vamos.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: lietadlo', correct: 'avión', vocab: 'avión', explanation: '"El avión" = lietadlo.' },
            { type: 'multiple_choice', prompt: 'Ktorý dopravný prostriedok je vlak?', options: ['tren', 'avión', 'barco', 'coche'], correct: 'tren', vocab: 'tren', explanation: '"El tren" = vlak.' },
            { type: 'multiple_choice', prompt: '"Voy al aeropuerto" znamená…', options: ['Idem na letisko', 'Idem na stanicu', 'Idem domov', 'Idem do školy'], correct: 'Idem na letisko', vocab: 'aeropuerto', explanation: '"El aeropuerto" = letisko.' },
            { type: 'fill_blank', prompt: 'Doplň: Un ___ (lístok) de tren.', correct: 'billete', vocab: 'billete', explanation: '"El billete" = lístok.' },
            { type: 'multiple_choice', prompt: 'Ktoré sloveso znamená "ísť"?', options: ['ir', 'ser', 'tener', 'estar'], correct: 'ir', vocab: 'ir', explanation: '"Ir" = ísť.' },
          ],
        },
      ],
    },
    {
      slug: 'plans',
      title: 'Plány a prázdniny',
      description: 'Povedz, čo budeš robiť, a zhrň si A1.',
      lessons: [
        {
          title: 'Moje plány',
          description: 'Hovor o budúcnosti pomocou "ir a + infinitív".',
          day: 23,
          minutes: 30,
          grammar: {
            slug: 'future_plans',
            title: 'Ir a + infinitív (budúcnosť)',
            explanation:
              'Budúcnosť tvoríš jednoducho: "ir a" + sloveso v infinitíve. "Voy a viajar" = budem cestovať / chystám sa cestovať.',
            rule: 'voy/vas/va/vamos a + infinitív. Voy a comer. ¿Qué vas a hacer? Vamos a cenar.',
            examples: [
              { spanish: 'Voy a viajar a España.', translation: 'Budem cestovať do Španielska.' },
              { spanish: '¿Qué vas a hacer?', translation: 'Čo budeš robiť?' },
              { spanish: 'Vamos a cenar.', translation: 'Pôjdeme večerať.' },
            ],
          },
          vocab: [
            { spanish: 'plan', translation: 'plán', pronunciation: 'PLAN', example: '¿Cuál es tu plan?', exampleTranslation: 'Aký je tvoj plán?', category: 'plans' },
            { spanish: 'vacaciones', translation: 'prázdniny', pronunciation: 'bah-kah-see-ON-es', example: 'Estoy de vacaciones.', exampleTranslation: 'Som na prázdninách.', category: 'plans' },
            { spanish: 'playa', translation: 'pláž', pronunciation: 'PLAH-yah', example: 'Voy a la playa.', exampleTranslation: 'Idem na pláž.', category: 'plans' },
            { spanish: 'montaña', translation: 'hory', pronunciation: 'mon-TAH-nyah', example: 'Las montañas son bonitas.', exampleTranslation: 'Hory sú krásne.', category: 'plans' },
            { spanish: 'viaje', translation: 'cesta', pronunciation: 'bee-AH-heh', example: '¡Buen viaje!', exampleTranslation: 'Šťastnú cestu!', category: 'plans' },
            { spanish: 'fin de semana', translation: 'víkend', pronunciation: 'FEEN deh seh-MEH-nah', example: '¿Qué haces el fin de semana?', exampleTranslation: 'Čo robíš cez víkend?', category: 'plans' },
            { spanish: 'futuro', translation: 'budúcnosť', pronunciation: 'foo-TOO-roh', example: 'En el futuro quiero viajar.', exampleTranslation: 'V budúcnosti chcem cestovať.', category: 'plans' },
            { spanish: 'pronto', translation: 'čoskoro', pronunciation: 'PRON-toh', example: 'Voy a llegar pronto.', exampleTranslation: 'Čoskoro prídem.', category: 'plans' },
            { spanish: 'este verano', translation: 'toto leto', pronunciation: 'ES-teh beh-RAH-noh', example: 'Este verano voy a España.', exampleTranslation: 'Toto leto idem do Španielska.', category: 'plans' },
            { spanish: 'el año que viene', translation: 'budúci rok', pronunciation: 'el AH-nyoh keh bee-EH-neh', example: 'El año que viene voy a estudiar.', exampleTranslation: 'Budúci rok budem študovať.', category: 'plans' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Ako povieš "budem cestovať"?', options: ['Voy a viajar', 'Viajo a', 'Vas a viajar', 'Voy viajar'], correct: 'Voy a viajar', grammar: 'future_plans', explanation: 'ir a + infinitív: voy a viajar.' },
            { type: 'fill_blank', prompt: 'Doplň: ¿Qué ___ a hacer? (budeš)', correct: 'vas', grammar: 'future_plans', explanation: 'S "tú" → vas a + infinitív.' },
            { type: 'multiple_choice', prompt: '"Vamos a cenar" znamená…', options: ['Pôjdeme večerať', 'Ideme pracovať', 'Ideme študovať', 'Ideme domov'], correct: 'Pôjdeme večerať', grammar: 'future_plans', explanation: '"Ir a + cenar" = pôjdeme večerať.' },
            { type: 'translation', prompt: 'Prelož do španielčiny: pláž', correct: 'playa', vocab: 'playa', explanation: '"La playa" = pláž.' },
            { type: 'multiple_choice', prompt: 'Ktoré znamená "prázdniny"?', options: ['vacaciones', 'viaje', 'plan', 'futuro'], correct: 'vacaciones', vocab: 'vacaciones', explanation: '"Las vacaciones" = prázdniny.' },
            { type: 'multiple_choice', prompt: '"Este verano" znamená…', options: ['toto leto', 'budúci rok', 'tento týždeň', 'tento víkend'], correct: 'toto leto', vocab: 'este verano', explanation: '"Este verano" = toto leto.' },
            { type: 'fill_blank', prompt: 'Doplň: Voy a ___ (cestovať) a España.', correct: 'viajar', vocab: 'viaje', explanation: 'Po "voy a" nasleduje infinitív: viajar.' },
            { type: 'multiple_choice', prompt: '"El año que viene" je…', options: ['budúci rok', 'toto leto', 'minulý rok', 'budúci mesiac'], correct: 'budúci rok', vocab: 'el año que viene', explanation: '"El año que viene" = budúci rok.' },
          ],
        },
        {
          title: 'Dovolenka — opakovanie',
          description: 'Zopakuj si kľúčové slovesá a slovnú zásobu A1.',
          day: 24,
          minutes: 30,
          grammar: {
            slug: 'review_verbs',
            title: 'Opakovanie: ser, tener, ir',
            explanation:
              'Tri najdôležitejšie slovesá A1: "ser" (byť — identita a pôvod), "tener" (mať — vlastníctvo a pocity) a "ir" (ísť — smer). Trénuj ich spolu v cestovných situáciách.',
            rule: 'ser → Soy de Eslovaquia. tener → Tengo hambre. ir → Voy a la playa. Spoj ich: "Tengo un viaje y voy a España."',
            examples: [
              { spanish: 'Soy de Eslovaquia.', translation: 'Som zo Slovenska.' },
              { spanish: 'Tengo hambre.', translation: 'Mám hlad.' },
              { spanish: 'Voy a la playa.', translation: 'Idem na pláž.' },
            ],
          },
          vocab: [
            { spanish: 'vuelo', translation: 'let', pronunciation: 'BWEH-loh', example: 'Mi vuelo sale a las ocho.', exampleTranslation: 'Môj let odchádza o ôsmej.', category: 'travel' },
            { spanish: 'destino', translation: 'destinácia', pronunciation: 'des-TEE-noh', example: '¿Cuál es tu destino?', exampleTranslation: 'Aká je tvoja destinácia?', category: 'travel' },
            { spanish: 'salida', translation: 'odchod', pronunciation: 'sah-LEE-dah', example: 'La salida está allí.', exampleTranslation: 'Odchod je tam.', category: 'travel' },
            { spanish: 'llegada', translation: 'príchod', pronunciation: 'yeh-GAH-dah', example: 'La llegada es a las diez.', exampleTranslation: 'Príchod je o desiatej.', category: 'travel' },
            { spanish: 'pasajero', translation: 'cestujúci', pronunciation: 'pah-sah-HEH-roh', example: 'Los pasajeros esperan.', exampleTranslation: 'Cestujúci čakajú.', category: 'travel' },
            { spanish: 'turista', translation: 'turista', pronunciation: 'too-REES-tah', example: 'Soy turista.', exampleTranslation: 'Som turista.', category: 'travel' },
            { spanish: 'mapa', translation: 'mapa', pronunciation: 'MAH-pah', example: '¿Dónde está el mapa?', exampleTranslation: 'Kde je mapa?', category: 'travel' },
            { spanish: 'foto', translation: 'fotografia', pronunciation: 'FOH-toh', example: 'Tomo una foto.', exampleTranslation: 'Odfo tím si.', category: 'travel' },
            { spanish: 'recuerdo', translation: 'suvenír', pronunciation: 'reh-KWEHR-doh', example: 'Compro un recuerdo.', exampleTranslation: 'Kupujem suvenír.', category: 'travel' },
            { spanish: 'regalo', translation: 'darček', pronunciation: 'reh-GAH-loh', example: 'Este es un regalo.', exampleTranslation: 'Toto je darček.', category: 'travel' },
          ],
          exercises: [
            { type: 'multiple_choice', prompt: 'Soy de Eslovaquia. Ktoré sloveso je to?', options: ['ser', 'tener', 'ir', 'estar'], correct: 'ser', grammar: 'review_verbs', explanation: '"Soy" je tvar slovesa "ser" (byť).' },
            { type: 'multiple_choice', prompt: 'Tengo hambre. "Tengo" je tvar slovesa…', options: ['tener', 'ser', 'ir', 'querer'], correct: 'tener', grammar: 'review_verbs', explanation: '"Tengo" = mám (tener).' },
            { type: 'fill_blank', prompt: 'Doplň: ___ a la playa. (idem)', correct: 'Voy', grammar: 'review_verbs', explanation: 'S "yo" pri "ir" → voy.' },
            { type: 'multiple_choice', prompt: 'Ktoré znamená "let"?', options: ['vuelo', 'salida', 'llegada', 'mapa'], correct: 'vuelo', vocab: 'vuelo', explanation: '"El vuelo" = let.' },
            { type: 'multiple_choice', prompt: '"La salida" znamená…', options: ['odchod', 'príchod', 'let', 'stanica'], correct: 'odchod', vocab: 'salida', explanation: '"La salida" = odchod; "la llegada" = príchod.' },
            { type: 'fill_blank', prompt: 'Doplň: Soy ___. (turista)', correct: 'turista', vocab: 'turista', explanation: '"Soy turista" = som turista.' },
            { type: 'multiple_choice', prompt: 'Ktoré znamená "mapa"?', options: ['mapa', 'foto', 'regalo', 'recuerdo'], correct: 'mapa', vocab: 'mapa', explanation: '"El mapa" = mapa.' },
            { type: 'multiple_choice', prompt: 'Compro un ___ (suvenír).', options: ['recuerdo', 'regalo', 'billete', 'vuelo'], correct: 'recuerdo', vocab: 'recuerdo', explanation: '"Un recuerdo" = suvenír.' },
          ],
        },
      ],
    },
  ],
};
